# EXERCISES_1_7 - v5.0 unified format

EXERCISES_1_7 = {
    1: [
        {
            'id': 's1_01',
            'title': '创建一个变量 name，赋值为 "张三"，然后打印它',
            'desc': '创建一个变量 name，赋值为 "张三"，然后打印它',
            'diff': 'basic',
            'kp': ['var_create', 'type_str', 'print_basic'],
            'hint': '变量名 = 值，然后用 print() 输出',
            'template': 'name =   # 填写值\nprint()  # 填写打印内容',
            'test_input': '',
            'answer': 'name = "张三"\nprint(name)',
            'expected': '张三',
            'explain': '变量赋值是Python最基础的操作：用=把值存入变量名，print()输出变量的值。',
            'difficulty': 'basic',
        },
        {
            'id': 's1_02',
            'title': '将字符串 "123" 转换为整数，加 10，打印结果',
            'desc': '将字符串 "123" 转换为整数，加 10，打印结果',
            'diff': 'basic',
            'kp': ['type_convert', 'op_arithmetic', 'print_basic'],
            'hint': '用 int() 转换，然后 + 10',
            'template': 'num =   # 填写值\nresult =   # 填写值\nprint()  # 填写打印内容',
            'test_input': '',
            'answer': 'num = int("123")\nresult = num + 10\nprint(result)',
            'expected': '133',
            'explain': "类型转换：int()把字符串转整数，转换后才能做数学运算。字符串'123'+10会报TypeError。",
            'difficulty': 'basic',
        },
        {
            'id': 's1_03',
            'title': '创建变量 price = 19.99，用 f-string 打印 "价格：19.99元"',
            'desc': '创建变量 price = 19.99，用 f-string 打印 "价格：19.99元"',
            'diff': 'basic',
            'kp': ['var_create', 'type_float', 'print_basic'],
            'hint': 'f"价格：{price}元"',
            'template': 'price =   # 填写值\nprint()  # 填写打印内容',
            'test_input': '',
            'answer': 'price = 19.99\nprint(f"价格：{price}元")',
            'expected': '价格：19.99元',
            'explain': 'f-string格式化字符串：在引号前加f，用{}嵌入变量或表达式。:.2f表示保留2位小数。',
            'difficulty': 'basic',
        },
        {
            'id': 's1_04',
            'title': '创建三个变量：a=10, b=3.14, c="hello"，分别打印它们的类型',
            'desc': '创建三个变量：a=10, b=3.14, c="hello"，分别打印它们的类型',
            'diff': 'intermediate',
            'kp': ['var_create', 'type_check', 'print_basic'],
            'hint': '用 type() 函数',
            'template': 'a =   # 填写值\nb =   # 填写值\nc =   # 填写值\nprint()  # 填写打印内容\nprint()  # 填写打印内容\nprint()  # 填写打印内容',
            'test_input': '',
            'answer': 'a = 10\nb = 3.14\nc = "hello"\nprint(type(a))\nprint(type(b))\nprint(type(c))',
            'expected': "<class 'int'>\n<class 'float'>\n<class 'str'>",
            'explain': "type()函数返回变量的类型。Python中10是int，3.14是float，'hello'是str。",
            'difficulty': 'intermediate',
        },
        {
            'id': 's1_05',
            'title': '交换两个变量 a=5, b=10 的值，打印交换后的结果',
            'desc': '交换两个变量 a=5, b=10 的值，打印交换后的结果',
            'diff': 'intermediate',
            'kp': ['var_create', 'print_basic'],
            'hint': '用临时变量：temp = a; a = b; b = temp',
            'template': 'a =   # 填写值\nb =   # 填写值\ntemp =   # 填写值\na =   # 填写值\nb =   # 填写值\nprint()  # 填写打印内容',
            'test_input': '',
            'answer': 'a = 5\nb = 10\ntemp = a\na = b\nb = temp\nprint(f"a={a}, b={b}")',
            'expected': 'a=10, b=5',
            'explain': 'Python特有的交换语法：a,b=b,a，无需临时变量。底层用了元组打包和解包。',
            'difficulty': 'intermediate',
        },
        {
            'id': 's1_06',
            'title': '用一行代码计算并打印 2 的 10 次方',
            'desc': '用一行代码计算并打印 2 的 10 次方',
            'diff': 'challenge',
            'kp': ['op_arithmetic', 'print_basic'],
            'hint': 'print(2 ** 10)',
            'template': 'print()  # 填写打印内容',
            'test_input': '',
            'answer': 'print(2 ** 10)',
            'expected': '1024',
            'explain': '**是幂运算符，2**10=1024。比用math.pow更简洁，且返回整数类型。',
            'difficulty': 'challenge',
        },
    ],
    2: [
        {
            'id': 's2_01',
            'title': '计算 17 除以 5 的商和余数，分别打印',
            'desc': '计算 17 除以 5 的商和余数，分别打印',
            'diff': 'basic',
            'kp': ['op_arithmetic', 'print_basic'],
            'hint': '17 // 5 得商，17 % 5 得余数',
            'template': 'quotient =   # 填写值\nremainder =   # 填写值\nprint()  # 填写打印内容\nprint()  # 填写打印内容',
            'test_input': '',
            'answer': 'quotient = 17 // 5\nremainder = 17 % 5\nprint(quotient)\nprint(remainder)',
            'expected': '3\n2',
            'explain': '//是整除（向下取整），%是取余。17//5=3, 17%5=2，验证：3*5+2=17。',
            'difficulty': 'basic',
        },
        {
            'id': 's2_02',
            'title': '判断 2024 是否为闰年，打印 True 或 False',
            'desc': '（能被4整除且不能被100整除，或能被400整除）',
            'diff': 'intermediate',
            'kp': ['op_arithmetic', 'op_compare', 'op_logical', 'print_basic'],
            'hint': 'year % 4 == 0 and year % 100 != 0 or year % 400 == 0',
            'template': 'year =   # 填写值\nis_leap =   # 填写值\nprint()  # 填写打印内容',
            'test_input': '',
            'answer': 'year = 2024\nis_leap = (year % 4 == 0 and year % 100 != 0) or (year % 400 == 0)\nprint(is_leap)',
            'expected': 'True',
            'explain': '闰年规则：(能被4整除且不能被100整除)或能被400整除。2024/4=506余0，非世纪年。',
            'difficulty': 'intermediate',
        },
        {
            'id': 's2_03',
            'title': '用 += 将变量 count 从 0 累加到 10（每次加2），打印结果',
            'desc': '用 += 将变量 count 从 0 累加到 10（每次加2），打印结果',
            'diff': 'basic',
            'kp': ['op_assign', 'var_create', 'print_basic'],
            'hint': 'count = 0, count += 2, 重复5次',
            'template': 'count =   # 填写值\n# ...\n# ...\n# ...\n# ...\n# ...\nprint()  # 填写打印内容',
            'test_input': '',
            'answer': 'count = 0\ncount += 2\ncount += 2\ncount += 2\ncount += 2\ncount += 2\nprint(count)',
            'expected': '10',
            'explain': '+=是复合赋值运算符，count+=2等价于count=count+2。循环5次从0加2。',
            'difficulty': 'basic',
        },
        {
            'id': 's2_04',
            'title': '计算圆的面积（半径 r=5，公式 pi*r*r），用 3.14159 代替 pi，打印结果保留2位小数',
            'desc': '计算圆的面积（半径 r=5，公式 pi*r*r），用 3.14159 代替 pi，打印结果保留2位小数',
            'diff': 'intermediate',
            'kp': ['op_arithmetic', 'type_float', 'print_basic'],
            'hint': 'f"{area:.2f}"',
            'template': 'r =   # 填写值\npi =   # 填写值\narea =   # 填写值\nprint()  # 填写打印内容',
            'test_input': '',
            'answer': 'r = 5\npi = 3.14159\narea = pi * r * r\nprint(f"{area:.2f}")',
            'expected': '78.54',
            'explain': '圆面积公式S=pi*r^2，f-string的:.2f格式化为2位小数。3.14159*25=78.54。',
            'difficulty': 'intermediate',
        },
        {
            'id': 's2_05',
            'title': '不使用 if，用一行表达式判断 15 是奇数还是偶数（打印 True 或 False）',
            'desc': '不使用 if，用一行表达式判断 15 是奇数还是偶数（打印 True 或 False）',
            'diff': 'challenge',
            'kp': ['op_arithmetic', 'op_compare', 'print_basic'],
            'hint': '15 % 2 == 0 判断偶数',
            'template': 'print()  # 填写打印内容',
            'test_input': '',
            'answer': 'print(15 % 2 == 0)',
            'expected': 'False',
            'explain': 'n%2==0判断偶数：偶数除以2余0。15%2=1→False，即15不是偶数。',
            'difficulty': 'challenge',
        },
    ],
    3: [
        {
            'id': 's3_01',
            'title': '根据变量 score=85 打印等级：90+优秀，60+及格，否则不及格',
            'desc': '根据变量 score=85 打印等级：90+优秀，60+及格，否则不及格',
            'diff': 'basic',
            'kp': ['if_elif', 'op_compare', 'print_basic'],
            'hint': '用 if-elif-else',
            'template': 'score =   # 填写值\nif score >= 90:\n    pass\nprint()  # 填写打印内容\n# ...\nprint()  # 填写打印内容\n# ...\nprint()  # 填写打印内容',
            'test_input': '',
            'answer': 'score = 85\nif score >= 90:\n    print("优秀")\nelif score >= 60:\n    print("及格")\nelse:\n    print("不及格")',
            'expected': '及格',
            'explain': 'if-elif-else从上到下判断，匹配第一个为真的分支。85>=60进入elif，不会继续检查else。',
            'difficulty': 'basic',
        },
        {
            'id': 's3_02',
            'title': '判断变量 num=42 是奇数还是偶数，打印结果',
            'desc': '判断变量 num=42 是奇数还是偶数，打印结果',
            'diff': 'basic',
            'kp': ['if_else', 'op_arithmetic', 'print_basic'],
            'hint': '用 % 2 == 0 判断偶数',
            'template': 'num =   # 填写值\nif num % 2 == 0:\n    pass\nprint()  # 填写打印内容\n# ...\nprint()  # 填写打印内容',
            'test_input': '',
            'answer': 'num = 42\nif num % 2 == 0:\n    print(f"{num} 是偶数")\nelse:\n    print(f"{num} 是奇数")',
            'expected': '42 是偶数',
            'explain': 'num%2判断奇偶：42%2=0→偶数。if-else二选一结构。',
            'difficulty': 'basic',
        },
        {
            'id': 's3_03',
            'title': '找出三个数 a=5, b=12, c=8 中的最大值并打印',
            'desc': '找出三个数 a=5, b=12, c=8 中的最大值并打印',
            'diff': 'intermediate',
            'kp': ['if_nested', 'op_compare', 'print_basic'],
            'hint': '用嵌套 if 或多个条件',
            'template': 'a =   # 填写值\nb =   # 填写值\nc =   # 填写值\nif a >= b and a >= c:\n    pass\nmax_val =   # 填写值\n# ...\nmax_val =   # 填写值\n# ...\nmax_val =   # 填写值\nprint()  # 填写打印内容',
            'test_input': '',
            'answer': 'a = 5\nb = 12\nc = 8\nif a >= b and a >= c:\n    max_val = a\nelif b >= a and b >= c:\n    max_val = b\nelse:\n    max_val = c\nprint(f"最大值是 {max_val}")',
            'expected': '最大值是 12',
            'explain': '方法一：用内置max(a,b,c)。方法二：先假设a最大，逐个比较更新。此答案用嵌套max。',
            'difficulty': 'intermediate',
        },
        {
            'id': 's3_04',
            'title': '判断 year=2100 是否为闰年（这次用 if-else）',
            'desc': '判断 year=2100 是否为闰年（这次用 if-else）',
            'diff': 'intermediate',
            'kp': ['if_else', 'op_logical', 'print_basic'],
            'hint': '能被4整除且不能被100整除，或能被400整除',
            'template': 'year =   # 填写值\nif (year % 4 == 0 and year % 100 != 0) or (year % 400 == 0):\n    pass\nprint()  # 填写打印内容\n# ...\nprint()  # 填写打印内容',
            'test_input': '',
            'answer': 'year = 2100\nif (year % 4 == 0 and year % 100 != 0) or (year % 400 == 0):\n    print(f"{year} 是闰年")\nelse:\n    print(f"{year} 不是闰年")',
            'expected': '2100 不是闰年',
            'explain': '世纪年(整百年)需要被400整除才是闰年。2100/400=5.25→不整除→非闰年。',
            'difficulty': 'intermediate',
        },
        {
            'id': 's3_05',
            'title': '计算 BMI=weight/height^2，根据 BMI 打印分类（<18.5偏瘦, 18.5-24.9正常, 25-29.9偏胖, >=30肥胖）',
            'desc': 'weight=70, height=1.75',
            'diff': 'challenge',
            'kp': ['if_elif', 'op_arithmetic', 'print_basic'],
            'hint': '先算 bmi，再用 if-elif-else 判断',
            'template': 'weight =   # 填写值\nheight =   # 填写值\nbmi =   # 填写值\nif bmi < 18.5:\n    pass\nprint()  # 填写打印内容\n# ...\nprint()  # 填写打印内容\n# ...\nprint()  # 填写打印内容\n# ...\nprint()  # 填写打印内容',
            'test_input': '',
            'answer': 'weight = 70\nheight = 1.75\nbmi = weight / (height ** 2)\nif bmi < 18.5:\n    print("偏瘦")\nelif bmi < 25:\n    print("正常")\nelif bmi < 30:\n    print("偏胖")\nelse:\n    print("肥胖")',
            'expected': '正常',
            'explain': 'BMI=体重/身高^2，多分支判断分类。18.5<=BMI<24是正常范围，多个elif逐级判断。',
            'difficulty': 'challenge',
        },
    ],
    4: [
        {
            'id': 's4_01',
            'title': '用 for 循环打印 1 到 10 的平方（每行一个）',
            'desc': '用 for 循环打印 1 到 10 的平方（每行一个）',
            'diff': 'basic',
            'kp': ['for_loop', 'range_func', 'op_arithmetic', 'print_basic'],
            'hint': 'for i in range(1, 11): print(i**2)',
            'template': 'for i in range(1, 11):\n    pass\nprint()  # 填写打印内容',
            'test_input': '',
            'answer': 'for i in range(1, 11):\n    print(i ** 2)',
            'expected': '1\n4\n9\n16\n25\n36\n49\n64\n81\n100',
            'explain': 'for i in range(1,11)遍历1到10，i**2计算平方。range(1,11)不包含11。',
            'difficulty': 'basic',
        },
        {
            'id': 's4_02',
            'title': '用 while 循环计算 1+2+...+100 的和并打印',
            'desc': '用 while 循环计算 1+2+...+100 的和并打印',
            'diff': 'basic',
            'kp': ['while_loop', 'op_assign', 'print_basic'],
            'hint': 'while i <= 100: total += i; i += 1',
            'template': 'total =   # 填写值\ni =   # 填写值\nwhile i <= 100:\n    pass\n# ...\n# ...\nprint()  # 填写打印内容',
            'test_input': '',
            'answer': 'total = 0\ni = 1\nwhile i <= 100:\n    total += i\n    i += 1\nprint(total)',
            'expected': '5050',
            'explain': 'while循环累加：初始化total=0, i=1，每次total+=i, i+=1，直到i>100退出。',
            'difficulty': 'basic',
        },
        {
            'id': 's4_03',
            'title': '打印 1 到 20 中的所有奇数（用 continue 跳过偶数）',
            'desc': '打印 1 到 20 中的所有奇数（用 continue 跳过偶数）',
            'diff': 'intermediate',
            'kp': ['for_loop', 'range_func', 'break_continue', 'print_basic'],
            'hint': 'if i % 2 == 0: continue',
            'template': 'for i in range(1, 21):\n    pass\n    if i % 2 == 0:\n        pass\n# ...\nprint()  # 填写打印内容',
            'test_input': '',
            'answer': 'for i in range(1, 21):\n    if i % 2 == 0:\n        continue\n    print(i)',
            'expected': '1\n3\n5\n7\n9\n11\n13\n15\n17\n19',
            'explain': 'continue跳过本次循环剩余部分，i%2==0时跳过（偶数不打印），只打印奇数。',
            'difficulty': 'intermediate',
        },
        {
            'id': 's4_04',
            'title': '找出 1 到 100 中第一个能被 7 整除的数并打印（用 break）',
            'desc': '找出 1 到 100 中第一个能被 7 整除的数并打印（用 break）',
            'diff': 'intermediate',
            'kp': ['for_loop', 'break_continue', 'op_arithmetic', 'print_basic'],
            'hint': 'if i % 7 == 0: print(i); break',
            'template': 'for i in range(1, 101):\n    pass\n    if i % 7 == 0:\n        pass\nprint()  # 填写打印内容\n# ...',
            'test_input': '',
            'answer': 'for i in range(1, 101):\n    if i % 7 == 0:\n        print(i)\n        break',
            'expected': '7',
            'explain': 'break立即退出循环。i%7==0时找到第一个7的倍数，break终止循环。',
            'difficulty': 'intermediate',
        },
        {
            'id': 's4_05',
            'title': '用嵌套循环打印如下三角形（5行）：',
            'desc': '*\n**\n***\n****\n*****',
            'diff': 'challenge',
            'kp': ['nested_loop', 'for_loop', 'print_basic'],
            'hint': '外层循环行数，内层循环每行的 * 个数',
            'template': 'for i in range(1, 6):\n    pass\nprint()  # 填写打印内容',
            'test_input': '',
            'answer': 'for i in range(1, 6):\n    print("*" * i)',
            'expected': '*\n**\n***\n****\n*****',
            'explain': "嵌套循环：外层控制行数(1~5)，内层打印i个星号。print('*'*i)利用字符串乘法更简洁。",
            'difficulty': 'challenge',
        },
        {
            'id': 's4_06',
            'title': '用循环计算 1! + 2! + 3! + 4! + 5! 并打印结果',
            'desc': '（n! = 1*2*3*...*n）',
            'diff': 'challenge',
            'kp': ['nested_loop', 'op_arithmetic', 'print_basic'],
            'hint': '外层循环 1-5，内层循环算阶乘',
            'template': 'total =   # 填写值\nfor n in range(1, 6):\n    pass\nfact =   # 填写值\n    for i in range(1, n + 1):\n        pass\n# ...\n# ...\nprint()  # 填写打印内容',
            'test_input': '',
            'answer': 'total = 0\nfor n in range(1, 6):\n    fact = 1\n    for i in range(1, n + 1):\n        fact *= i\n    total += fact\nprint(total)',
            'expected': '153',
            'explain': '双重循环：外层遍历1~5，内层算阶乘(factorial)，同时累加到total。',
            'difficulty': 'challenge',
        },
    ],
    5: [
        {
            'id': 's5_01',
            'title': '写一个函数 is_even(n)，判断 n 是否为偶数，返回 True 或 False',
            'desc': '然后调用 print(is_even(4))',
            'diff': 'basic',
            'kp': ['func_def', 'func_return', 'op_arithmetic'],
            'hint': 'def is_even(n): return n % 2 == 0',
            'template': 'def is_even(n):\n    pass\nprint()  # 填写打印内容',
            'test_input': '',
            'answer': 'def is_even(n):\n    return n % 2 == 0\n\nprint(is_even(4))',
            'expected': 'True',
            'explain': '函数定义用def，return返回结果。n%2==0是布尔表达式，直接返回True/False。',
            'difficulty': 'basic',
        },
        {
            'id': 's5_02',
            'title': '写一个函数 greet(name, msg="你好")，打印问候语',
            'desc': '然后调用 greet("张三") 和 greet("李四", "欢迎")',
            'diff': 'basic',
            'kp': ['func_def', 'func_default', 'print_basic'],
            'hint': '默认参数 msg="你好"',
            'template': 'def greet(name, msg="你好"):\n    pass\n# ...\n# ...',
            'test_input': '',
            'answer': 'def greet(name, msg="你好"):\n    print(f"{msg}，{name}！")\n\ngreet("张三")\ngreet("李四", "欢迎")',
            'expected': '你好，张三！\n欢迎，李四！',
            'explain': "默认参数msg='你好'：调用greet('张三')用默认值，greet('张三','早上好')覆盖默认值。",
            'difficulty': 'basic',
        },
        {
            'id': 's5_03',
            'title': '写一个函数 max_of_three(a, b, c) 返回三个数中的最大值',
            'desc': '然后调用 print(max_of_three(5, 12, 8))',
            'diff': 'intermediate',
            'kp': ['func_def', 'func_return', 'if_elif'],
            'hint': '可以用多个 if 或 max() 函数',
            'template': 'def max_of_three(a, b, c):\n    pass\nprint()  # 填写打印内容',
            'test_input': '',
            'answer': 'def max_of_three(a, b, c):\n    if a >= b:\n        bigger = a\n    else:\n        bigger = b\n    if bigger >= c:\n        return bigger\n    else:\n        return c\n\nprint(max_of_three(5, 12, 8))',
            'expected': '12',
            'explain': '先比较a和b得较大值，再与c比较。也可用return max(a,b,c)一行搞定。',
            'difficulty': 'intermediate',
        },
        {
            'id': 's5_04',
            'title': '写一个函数 fibonacci(n) 返回第 n 个斐波那契数',
            'desc': '（fib(1)=1, fib(2)=1, fib(n)=fib(n-1)+fib(n-2)）\n然后调用 print(fibonacci(6))',
            'diff': 'challenge',
            'kp': ['func_def', 'func_return', 'while_loop', 'op_assign'],
            'hint': '用循环，a, b = b, a+b',
            'template': 'def fibonacci(n):\n    pass\nprint()  # 填写打印内容',
            'test_input': '',
            'answer': 'def fibonacci(n):\n    if n <= 2:\n        return 1\n    a, b = 1, 1\n    for _ in range(3, n + 1):\n        a, b = b, a + b\n    return b\n\nprint(fibonacci(6))',
            'expected': '8',
            'explain': '斐波那契递归：f(0)=0, f(1)=1, f(n)=f(n-1)+f(n-2)。注意递归效率低，n大时用迭代更好。',
            'difficulty': 'challenge',
        },
        {
            'id': 's5_05',
            'title': '写一个函数 reverse_string(s) 返回反转后的字符串',
            'desc': '然后调用 print(reverse_string("hello"))',
            'diff': 'intermediate',
            'kp': ['func_def', 'func_return', 'str_methods'],
            'hint': 's[::-1] 或用循环',
            'template': 'def reverse_string(s):\n    pass\nprint()  # 填写打印内容',
            'test_input': '',
            'answer': 'def reverse_string(s):\n    return s[::-1]\n\nprint(reverse_string("hello"))',
            'expected': 'olleh',
            'explain': '切片[::-1]反转字符串，等价于s[len(s)-1::-1]。比循环逆序拼接更Pythonic。',
            'difficulty': 'intermediate',
        },
    ],
    6: [
        {
            'id': 's6_01',
            'title': '创建列表 [1,2,3,4,5]，用 append 添加 6，然后打印列表',
            'desc': '创建列表 [1,2,3,4,5]，用 append 添加 6，然后打印列表',
            'diff': 'basic',
            'kp': ['list_create', 'list_methods', 'print_basic'],
            'hint': 'lst.append(6)',
            'template': 'numbers =   # 填写值\n# ...\nprint()  # 填写打印内容',
            'test_input': '',
            'answer': 'numbers = [1, 2, 3, 4, 5]\nnumbers.append(6)\nprint(numbers)',
            'expected': '[1, 2, 3, 4, 5, 6]',
            'explain': 'append()在列表末尾添加一个元素。列表是可变的，append直接修改原列表，返回None。',
            'difficulty': 'basic',
        },
        {
            'id': 's6_02',
            'title': '用列表推导式生成 1 到 10 中所有偶数的平方',
            'desc': '用列表推导式生成 1 到 10 中所有偶数的平方',
            'diff': 'intermediate',
            'kp': ['list_comprehension', 'op_arithmetic'],
            'hint': '[x**2 for x in range(1, 11) if x % 2 == 0]',
            'template': 'evens_sq =   # 填写值\nprint()  # 填写打印内容',
            'test_input': '',
            'answer': 'evens_sq = [x**2 for x in range(1, 11) if x % 2 == 0]\nprint(evens_sq)',
            'expected': '[4, 16, 36, 64, 100]',
            'explain': '列表推导式：[x**2 for x in range(1,11) if x%2==0]，一行完成过滤+变换。',
            'difficulty': 'intermediate',
        },
        {
            'id': 's6_03',
            'title': '遍历列表 ["苹果","香蕉","橙子"]，打印每个水果及其索引',
            'desc': '遍历列表 ["苹果","香蕉","橙子"]，打印每个水果及其索引',
            'diff': 'basic',
            'kp': ['list_iter', 'print_basic'],
            'hint': 'for i, fruit in enumerate(lst):',
            'template': 'fruits =   # 填写值\nfor i, fruit in enumerate(fruits):\n    pass\nprint()  # 填写打印内容',
            'test_input': '',
            'answer': 'fruits = ["苹果", "香蕉", "橙子"]\nfor i, fruit in enumerate(fruits):\n    print(f"{i}: {fruit}")',
            'expected': '0: 苹果\n1: 香蕉\n2: 橙子',
            'explain': 'enumerate()同时返回索引和值：for i, fruit in enumerate(lst)，比range(len(lst))更优雅。',
            'difficulty': 'basic',
        },
        {
            'id': 's6_04',
            'title': '将列表 [3, 1, 4, 1, 5, 9, 2, 6] 排序后打印（从小到大）',
            'desc': '将列表 [3, 1, 4, 1, 5, 9, 2, 6] 排序后打印（从小到大）',
            'diff': 'basic',
            'kp': ['list_methods', 'print_basic'],
            'hint': 'lst.sort() 或 sorted(lst)',
            'template': 'numbers =   # 填写值\n# ...\nprint()  # 填写打印内容',
            'test_input': '',
            'answer': 'numbers = [3, 1, 4, 1, 5, 9, 2, 6]\nnumbers.sort()\nprint(numbers)',
            'expected': '[1, 1, 2, 3, 4, 5, 6, 9]',
            'explain': 'sort()原地排序（修改原列表），sorted()返回新列表。都是默认升序。',
            'difficulty': 'basic',
        },
        {
            'id': 's6_05',
            'title': '统计列表 [1, 2, 3, 2, 1, 3, 2, 1] 中每个数字出现的次数，用字典打印',
            'desc': '统计列表 [1, 2, 3, 2, 1, 3, 2, 1] 中每个数字出现的次数，用字典打印',
            'diff': 'challenge',
            'kp': ['list_iter', 'dict_create', 'print_basic'],
            'hint': '用字典计数，遍历列表',
            'template': 'nums =   # 填写值\ncounts =   # 填写值\nfor n in nums:\n    pass\n# ...\nprint()  # 填写打印内容',
            'test_input': '',
            'answer': 'nums = [1, 2, 3, 2, 1, 3, 2, 1]\ncounts = {}\nfor n in nums:\n    counts[n] = counts.get(n, 0) + 1\nprint(counts)',
            'expected': '{1: 3, 2: 3, 3: 2}',
            'explain': '字典统计频次：遍历列表，d[item]=d.get(item,0)+1，get(key,default)避免KeyError。',
            'difficulty': 'challenge',
        },
        {
            'id': 's6_06',
            'title': '用列表推导式将 ["hello", "world", "python"] 转为大写列表',
            'desc': '用列表推导式将 ["hello", "world", "python"] 转为大写列表',
            'diff': 'intermediate',
            'kp': ['list_comprehension', 'str_methods'],
            'hint': '[s.upper() for s in lst]',
            'template': 'words =   # 填写值\nupper_words =   # 填写值\nprint()  # 填写打印内容',
            'test_input': '',
            'answer': 'words = ["hello", "world", "python"]\nupper_words = [w.upper() for w in words]\nprint(upper_words)',
            'expected': "['HELLO', 'WORLD', 'PYTHON']",
            'explain': '列表推导式+.upper()：[s.upper() for s in lst]，对每个元素调用字符串方法。',
            'difficulty': 'intermediate',
        },
    ],
    7: [
        {
            'id': 's7_01',
            'title': '创建元组 point = (3, 4)，打印它的第一个和第二个元素',
            'desc': '创建元组 point = (3, 4)，打印它的第一个和第二个元素',
            'diff': 'basic',
            'kp': ['tuple_create', 'list_index'],
            'hint': 'point[0] 和 point[1]',
            'template': 'point =   # 填写值\nprint()  # 填写打印内容\nprint()  # 填写打印内容',
            'test_input': '',
            'answer': 'point = (3, 4)\nprint(point[0])\nprint(point[1])',
            'expected': '3\n4',
            'explain': '元组索引和列表一样从0开始。point[0]是第一个元素3，point[1]是第二个元素4。',
            'difficulty': 'basic',
        },
        {
            'id': 's7_02',
            'title': '用元组解包交换 a=10, b=20 的值，打印交换结果',
            'desc': '用元组解包交换 a=10, b=20 的值，打印交换结果',
            'diff': 'basic',
            'kp': ['tuple_unpack', 'print_basic'],
            'hint': 'a, b = b, a',
            'template': 'a =   # 填写值\nb =   # 填写值\n# ...\nprint()  # 填写打印内容',
            'test_input': '',
            'answer': 'a = 10\nb = 20\na, b = b, a\nprint(f"a={a}, b={b}")',
            'expected': 'a=20, b=10',
            'explain': '元组解包交换：a,b=b,a，右边先打包成元组(20,10)，再解包赋值。无需临时变量。',
            'difficulty': 'basic',
        },
        {
            'id': 's7_03',
            'title': '创建坐标列表 [(1,2), (3,4), (5,6)]，遍历并打印每个坐标的 x 和 y',
            'desc': '创建坐标列表 [(1,2), (3,4), (5,6)]，遍历并打印每个坐标的 x 和 y',
            'diff': 'intermediate',
            'kp': ['tuple_unpack', 'list_iter'],
            'hint': 'for x, y in coords:',
            'template': 'coords =   # 填写值\nfor x, y in coords:\n    pass\nprint()  # 填写打印内容',
            'test_input': '',
            'answer': 'coords = [(1, 2), (3, 4), (5, 6)]\nfor x, y in coords:\n    print(f"x={x}, y={y}")',
            'expected': 'x=1, y=2\nx=3, y=4\nx=5, y=6',
            'explain': '遍历元组列表时直接解包：for x, y in points，每个元素是元组，可同时取出两个值。',
            'difficulty': 'intermediate',
        },
        {
            'id': 's7_04',
            'title': '验证元组不可变：尝试修改 t = (1,2,3) 的第一个元素为 9，用 try-except 捕获 TypeError 并打印"元组不可变"',
            'desc': '验证元组不可变：尝试修改 t = (1,2,3) 的第一个元素为 9，用 try-except 捕获 TypeError 并打印"元组不可变"',
            'diff': 'challenge',
            'kp': ['tuple_immutable', 'try_except'],
            'hint': 'try: t[0] = 9 except TypeError: print(...)',
            'template': 't =   # 填写值\n# ...\n# ...\n# ...\nprint()  # 填写打印内容',
            'test_input': '',
            'answer': 't = (1, 2, 3)\ntry:\n    t[0] = 9\nexcept TypeError:\n    print("元组不可变")',
            'expected': '元组不可变',
            'explain': '元组不可变，t[0]=9会抛TypeError。try-except捕获异常，说明元组的不可变特性。',
            'difficulty': 'challenge',
        },
        {
            'id': 's7_05',
            'title': '创建一个含3个坐标的元组列表 points = [(0,0), (1,1), (2,3)]，用循环打印每个点到原点的距离（保留2位小数）',
            'desc': '创建一个含3个坐标的元组列表 points = [(0,0), (1,1), (2,3)]，用循环打印每个点到原点的距离（保留2位小数）',
            'diff': 'intermediate',
            'kp': ['tuple_unpack', 'list_iter', 'op_arithmetic'],
            'hint': '距离 = (x**2 + y**2)**0.5，用 f"{d:.2f}"',
            'template': 'points =   # 填写值\nfor x, y in points:\n    pass\nd =   # 填写值\nprint()  # 填写打印内容',
            'test_input': '',
            'answer': 'points = [(0, 0), (1, 1), (2, 3)]\nfor x, y in points:\n    d = (x**2 + y**2)**0.5\n    print(f"{d:.2f}")',
            'expected': '0.00\n1.41\n3.61',
            'explain': '欧几里得距离：sqrt((x2-x1)^2+(y2-y1)^2)。解包x,y后代入公式计算。',
            'difficulty': 'intermediate',
        },
        {
            'id': 's7_06',
            'title': '用元组实现：函数返回商和余数。写 divmod_custom(a, b) 返回 (a//b, a%b)，调用 print(divmod_custom(17, 5))',
            'desc': '用元组实现：函数返回商和余数。写 divmod_custom(a, b) 返回 (a//b, a%b)，调用 print(divmod_custom(17, 5))',
            'diff': 'intermediate',
            'kp': ['tuple_create', 'func_def', 'func_return'],
            'hint': 'return (a // b, a % b)',
            'template': 'def divmod_custom(a, b):\n    pass\nprint()  # 填写打印内容',
            'test_input': '',
            'answer': 'def divmod_custom(a, b):\n    return (a // b, a % b)\n\nprint(divmod_custom(17, 5))',
            'expected': '(3, 2)',
            'explain': '函数返回多个值本质是返回元组。divmod返回(商,余数)，调用时可用a,b=divmod(17,5)解包。',
            'difficulty': 'intermediate',
        },
        {
            'id': 's7_07',
            'title': '用 * 解包：first, *rest = (1, 2, 3, 4, 5)，打印 first 和 rest',
            'desc': '用 * 解包：first, *rest = (1, 2, 3, 4, 5)，打印 first 和 rest',
            'diff': 'challenge',
            'kp': ['tuple_unpack'],
            'hint': '*rest 收集剩余元素为列表',
            'template': '# ...\nprint()  # 填写打印内容\nprint()  # 填写打印内容',
            'test_input': '',
            'answer': 'first, *rest = (1, 2, 3, 4, 5)\nprint(first)\nprint(rest)',
            'expected': '1\n[2, 3, 4, 5]',
            'explain': '星号解包：first拿第一个，*rest收集剩余为列表。(1,2,3,4,5)→first=1,rest=[2,3,4,5]。',
            'difficulty': 'challenge',
        },
    ],
}
