# EXERCISES_14_18 - v5.0 unified format

EXERCISES_14_18 = {
    14: [
        {
            'id': 's14_01',
            'title': '用 re.findall 提取字符串 "价格25元，优惠10元，合计15元" 中的所有数字',
            'desc': '用 re.findall 提取字符串 "价格25元，优惠10元，合计15元" 中的所有数字',
            'diff': 'basic',
            'kp': ['regex_basic', 'regex_meta', 'print_basic'],
            'hint': "re.findall(r'\\d+', text)",
            'template': 'import re\ntext =   # 填写值\nnums =   # 填写值\nprint()  # 填写打印内容',
            'test_input': '',
            'answer': 'import re\ntext = "价格25元，优惠10元，合计15元"\nnums = re.findall(r"\\d+", text)\nprint(nums)',
            'expected': "['25', '10', '15']",
            'explain': "re.findall(r'\\d+', s)提取所有连续数字。\\d匹配数字，+表示一个或多个。",
            'difficulty': 'basic',
        },
        {
            'id': 's14_02',
            'title': '用 re.search 判断字符串 "我的手机号13812345678" 中是否包含手机号（1开头11位数字）',
            'desc': '用 re.search 判断字符串 "我的手机号13812345678" 中是否包含手机号（1开头11位数字）',
            'diff': 'basic',
            'kp': ['regex_quantifier', 'print_basic'],
            'hint': "re.search(r'1\\d{10}', text)",
            'template': 'import re\ntext =   # 填写值\nresult =   # 填写值\nprint()  # 填写打印内容',
            'test_input': '',
            'answer': 'import re\ntext = "我的手机号13812345678"\nresult = re.search(r"1\\d{10}", text)\nprint(bool(result))',
            'expected': 'True',
            'explain': "手机号正则r'1[3-9]\\d{9}'：1开头+第二位3-9+9位数字。re.search在字符串中搜索匹配。",
            'difficulty': 'basic',
        },
        {
            'id': 's14_03',
            'title': '用 re.sub 把字符串 "电话：021-12345678" 中的所有数字替换为 #',
            'desc': '用 re.sub 把字符串 "电话：021-12345678" 中的所有数字替换为 #',
            'diff': 'basic',
            'kp': ['regex_sub', 'print_basic'],
            'hint': "re.sub(r'\\d', '#', text)",
            'template': 'import re\ntext =   # 填写值\nresult =   # 填写值\nprint()  # 填写打印内容',
            'test_input': '',
            'answer': 'import re\ntext = "电话：021-12345678"\nresult = re.sub(r"\\d", "#", text)\nprint(result)',
            'expected': '电话：###-########',
            'explain': "re.sub(r'\\d', '#', s)将每个数字替换为#。\\d匹配单个数字，#是替换内容。",
            'difficulty': 'basic',
        },
        {
            'id': 's14_04',
            'title': '用 re.findall 提取 "联系 admin@test.com 或 info@example.org" 中的所有邮箱地址',
            'desc': '用 re.findall 提取 "联系 admin@test.com 或 info@example.org" 中的所有邮箱地址',
            'diff': 'intermediate',
            'kp': ['regex_charset', 'regex_practice', 'print_basic'],
            'hint': "re.findall(r'[\\w.+-]+@[\\w-]+\\.[\\w.]+', text)",
            'template': 'import re\ntext =   # 填写值\nemails =   # 填写值\nprint()  # 填写打印内容',
            'test_input': '',
            'answer': 'import re\ntext = "联系 admin@test.com 或 info@example.org"\nemails = re.findall(r"[\\w.+-]+@[\\w-]+\\.[\\w.]+", text)\nprint(emails)',
            'expected': "['admin@test.com', 'info@example.org']",
            'explain': "邮箱正则r'[\\w.+-]+@[\\w-]+\\.[\\w.]+'：用户名@域名.后缀。\\w匹配字母数字下划线。",
            'difficulty': 'intermediate',
        },
        {
            'id': 's14_05',
            'title': '用分组提取日期 "2025-01-15" 中的年月日，分别打印',
            'desc': '用分组提取日期 "2025-01-15" 中的年月日，分别打印',
            'diff': 'intermediate',
            'kp': ['regex_group', 'print_basic'],
            'hint': "re.search(r'(\\d{4})-(\\d{2})-(\\d{2})', text).group(1)",
            'template': 'import re\ntext =   # 填写值\nm =   # 填写值\nprint()  # 填写打印内容\nprint()  # 填写打印内容\nprint()  # 填写打印内容',
            'test_input': '',
            'answer': 'import re\ntext = "2025-01-15"\nm = re.search(r"(\\d{4})-(\\d{2})-(\\d{2})", text)\nprint(f"年：{m.group(1)}")\nprint(f"月：{m.group(2)}")\nprint(f"日：{m.group(3)}")',
            'expected': '年：2025\n月：01\n日：15',
            'explain': '分组用()捕获，match.group(1/2/3)分别获取年/月/日。\\d{4}-\\d{2}-\\d{2}匹配日期格式。',
            'difficulty': 'intermediate',
        },
        {
            'id': 's14_06',
            'title': '用 re.compile 编译手机号正则，然后验证 "13812345678" 和 "12345" 是否匹配',
            'desc': '用 re.compile 编译手机号正则，然后验证 "13812345678" 和 "12345" 是否匹配',
            'diff': 'challenge',
            'kp': ['regex_compile', 'print_basic'],
            'hint': "pattern = re.compile(r'^1[3-9]\\d{9}$'); pattern.match(s)",
            'template': 'import re\nphone_pattern =   # 填写值\nprint()  # 填写打印内容\nprint()  # 填写打印内容',
            'test_input': '',
            'answer': 'import re\nphone_pattern = re.compile(r"^1[3-9]\\d{9}$")\nprint(bool(phone_pattern.match("13812345678")))\nprint(bool(phone_pattern.match("12345")))',
            'expected': 'True\nFalse',
            'explain': 're.compile预编译正则，提升多次匹配性能。pattern.match()/fullmatch()验证匹配。',
            'difficulty': 'challenge',
        },
    ],
    15: [
        {
            'id': 's15_01',
            'title': '创建一个 Dog 类，有 name 和 age 属性，有 bark() 方法返回 "{name}：汪汪！"',
            'desc': '创建一个 Dog 类，有 name 和 age 属性，有 bark() 方法返回 "{name}：汪汪！"',
            'diff': 'basic',
            'kp': ['oop_class_object', 'oop_init_self', 'print_basic'],
            'hint': 'class Dog: def __init__(self, name, age): ...',
            'template': 'class Dog:\n    def __init__(self, name, age):\n        pass\n    def bark(self):\n        pass\ndog =   # 填写值\nprint()  # 填写打印内容',
            'test_input': '',
            'answer': 'class Dog:\n    def __init__(self, name, age):\n        self.name = name\n        self.age = age\n    def bark(self):\n        return f"{self.name}：汪汪！"\n\ndog = Dog("旺财", 3)\nprint(dog.bark())',
            'expected': '旺财：汪汪！',
            'explain': '__init__是构造方法，self代表实例本身。实例属性self.name在构造时赋值。',
            'difficulty': 'basic',
        },
        {
            'id': 's15_02',
            'title': '创建 Animal 类有 speak() 方法返回 "..."，创建 Cat 类继承 Animal，重写 speak() 返回 "{name}：喵～"',
            'desc': '创建 Animal 类有 speak() 方法返回 "..."，创建 Cat 类继承 Animal，重写 speak() 返回 "{name}：喵～"',
            'diff': 'basic',
            'kp': ['oop_inheritance', 'print_basic'],
            'hint': 'class Cat(Animal): def speak(self): ...',
            'template': 'class Animal:\n    def __init__(self, name):\n        pass\n    def speak(self):\n        pass\nclass Cat(Animal):\n    def speak(self):\n        pass\ncat =   # 填写值\nprint()  # 填写打印内容',
            'test_input': '',
            'answer': 'class Animal:\n    def __init__(self, name):\n        self.name = name\n    def speak(self):\n        return "..."\n\nclass Cat(Animal):\n    def speak(self):\n        return f"{self.name}：喵～"\n\ncat = Cat("小花")\nprint(cat.speak())',
            'expected': '小花：喵～',
            'explain': '继承：class Cat(Animal)，子类重写父类方法。super()可调用父类版本，这里直接重写speak()。',
            'difficulty': 'basic',
        },
        {
            'id': 's15_03',
            'title': '创建 BankAccount 类，有 owner 和 _balance 属性，deposit(amount) 存钱，withdraw(amount) 取钱，用 @property 读取余额',
            'desc': '创建 BankAccount 类，有 owner 和 _balance 属性，deposit(amount) 存钱，withdraw(amount) 取钱，用 @property 读取余额',
            'diff': 'intermediate',
            'kp': ['oop_encapsulation', 'oop_property', 'print_basic'],
            'hint': '@property def balance(self): return self._balance',
            'template': 'class BankAccount:\n    def __init__(self, owner, balance=0):\n        pass\n    def deposit(self, amount):\n        pass\n    def withdraw(self, amount):\n        pass\n    @property\n    def balance(self):\n        pass\nacc =   # 填写值\n# ...\n# ...\nprint()  # 填写打印内容',
            'test_input': '',
            'answer': 'class BankAccount:\n    def __init__(self, owner, balance=0):\n        self.owner = owner\n        self._balance = balance\n    def deposit(self, amount):\n        if amount > 0:\n            self._balance += amount\n    def withdraw(self, amount):\n        if 0 < amount <= self._balance:\n            self._balance -= amount\n    @property\n    def balance(self):\n        return self._balance\n\nacc = BankAccount("张三", 1000)\nacc.deposit(500)\nacc.withdraw(200)\nprint(acc.balance)',
            'expected': '1300',
            'explain': '_balance是约定私有属性(单下划线前缀)。deposit/withdraw修改余额，提供受控访问。',
            'difficulty': 'intermediate',
        },
        {
            'id': 's15_04',
            'title': '创建 GuideDog 类继承 Dog（有 name, age），新增 owner 属性，用 super() 调用父类 __init__',
            'desc': '创建 GuideDog 类继承 Dog（有 name, age），新增 owner 属性，用 super() 调用父类 __init__',
            'diff': 'intermediate',
            'kp': ['oop_inheritance', 'oop_super', 'print_basic'],
            'hint': 'super().__init__(name, age)',
            'template': 'class Dog:\n    def __init__(self, name, age):\n        pass\n    def bark(self):\n        pass\nclass GuideDog(Dog):\n    def __init__(self, name, age, owner):\n        pass\n    def guide(self):\n        pass\ngd =   # 填写值\nprint()  # 填写打印内容\nprint()  # 填写打印内容',
            'test_input': '',
            'answer': 'class Dog:\n    def __init__(self, name, age):\n        self.name = name\n        self.age = age\n    def bark(self):\n        return f"{self.name}：汪汪！"\n\nclass GuideDog(Dog):\n    def __init__(self, name, age, owner):\n        super().__init__(name, age)\n        self.owner = owner\n    def guide(self):\n        return f"{self.name}正在引导{self.owner}"\n\ngd = GuideDog("路路", 3, "王先生")\nprint(gd.bark())\nprint(gd.guide())',
            'expected': '路路：汪汪！\n路路正在引导王先生',
            'explain': 'super().__init__(name, age)调用父类构造方法初始化继承的属性。子类新增owner属性。',
            'difficulty': 'intermediate',
        },
        {
            'id': 's15_05',
            'title': '写一个 animal_concert 函数，接收 Animal 列表，对每个调用 speak()，体现多态',
            'desc': '写一个 animal_concert 函数，接收 Animal 列表，对每个调用 speak()，体现多态',
            'diff': 'challenge',
            'kp': ['oop_polymorphism', 'print_basic'],
            'hint': 'def animal_concert(animals): for a in animals: print(a.speak())',
            'template': 'class Animal:\n    def __init__(self, name):\n        pass\n    def speak(self):\n        pass\nclass Cat(Animal):\n    def speak(self):\n        pass\nclass Dog(Animal):\n    def speak(self):\n        pass\ndef animal_concert(animals):\n    pass\nanimals =   # 填写值\n# ...',
            'test_input': '',
            'answer': 'class Animal:\n    def __init__(self, name):\n        self.name = name\n    def speak(self):\n        return "..."\n\nclass Cat(Animal):\n    def speak(self):\n        return f"{self.name}：喵～"\n\nclass Dog(Animal):\n    def speak(self):\n        return f"{self.name}：汪汪！"\n\ndef animal_concert(animals):\n    for a in animals:\n        print(a.speak())\n\nanimals = [Cat("小花"), Dog("旺财"), Cat("咪咪")]\nanimal_concert(animals)',
            'expected': '小花：喵～\n旺财：汪汪！\n咪咪：喵～',
            'explain': '多态：不同类型的对象调用同名方法speak()产生不同结果。函数不关心具体类型，只关心接口。',
            'difficulty': 'challenge',
        },
    ],
    16: [
        {
            'id': 's16_01',
            'title': '创建 Vector 类，有 x/y 属性，实现 __add__ 让 v1+v2 返回新 Vector，实现 __str__ 返回 "Vector(x, y)"',
            'desc': '创建 Vector 类，有 x/y 属性，实现 __add__ 让 v1+v2 返回新 Vector，实现 __str__ 返回 "Vector(x, y)"',
            'diff': 'basic',
            'kp': ['oop_magic_method', 'print_basic'],
            'hint': 'def __add__(self, other): return Vector(self.x+other.x, self.y+other.y)',
            'template': 'class Vector:\n    def __init__(self, x, y):\n        pass\n    def __add__(self, other):\n        pass\n    def __str__(self):\n        pass\nv1 =   # 填写值\nv2 =   # 填写值\nprint()  # 填写打印内容',
            'test_input': '',
            'answer': 'class Vector:\n    def __init__(self, x, y):\n        self.x = x\n        self.y = y\n    def __add__(self, other):\n        return Vector(self.x + other.x, self.y + other.y)\n    def __str__(self):\n        return f"Vector({self.x}, {self.y})"\n\nv1 = Vector(3, 4)\nv2 = Vector(1, 2)\nprint(v1 + v2)',
            'expected': 'Vector(4, 6)',
            'explain': '__add__魔术方法重载+运算符。return Vector(self.x+other.x, self.y+other.y)返回新对象。',
            'difficulty': 'basic',
        },
        {
            'id': 's16_02',
            'title': '创建 Date 类，用 @classmethod 写 from_string("2025-01-15") 工厂方法创建对象',
            'desc': '创建 Date 类，用 @classmethod 写 from_string("2025-01-15") 工厂方法创建对象',
            'diff': 'intermediate',
            'kp': ['oop_classmethod', 'print_basic'],
            'hint': "@classmethod def from_string(cls, s): y,m,d = s.split('-')",
            'template': 'class Date:\n    def __init__(self, year, month, day):\n        pass\n    @classmethod\n    def from_string(cls, date_str):\n        pass\n    def __str__(self):\n        pass\nd =   # 填写值\nprint()  # 填写打印内容',
            'test_input': '',
            'answer': 'class Date:\n    def __init__(self, year, month, day):\n        self.year = year\n        self.month = month\n        self.day = day\n    @classmethod\n    def from_string(cls, date_str):\n        y, m, d = date_str.split("-")\n        return cls(int(y), int(m), int(d))\n    def __str__(self):\n        return f"{self.year}-{self.month:02d}-{self.day:02d}"\n\nd = Date.from_string("2025-01-15")\nprint(d)',
            'expected': '2025-01-15',
            'explain': '@classmethod的第一个参数是cls(类本身)，不是实例。适合做替代构造方法，如从字符串创建对象。',
            'difficulty': 'intermediate',
        },
        {
            'id': 's16_03',
            'title': '创建 Date 类，用 @staticmethod 写 is_valid("2025-01-15") 检查日期格式是否合法（3个数字部分）',
            'desc': '创建 Date 类，用 @staticmethod 写 is_valid("2025-01-15") 检查日期格式是否合法（3个数字部分）',
            'diff': 'intermediate',
            'kp': ['oop_staticmethod', 'print_basic'],
            'hint': "@staticmethod def is_valid(s): parts = s.split('-')",
            'template': 'class Date:\n    def is_valid(date_str):\n        pass\nprint()  # 填写打印内容\nprint()  # 填写打印内容',
            'test_input': '',
            'answer': 'class Date:\n    @staticmethod\n    def is_valid(date_str):\n        parts = date_str.split("-")\n        return len(parts) == 3 and all(p.isdigit() for p in parts)\n\nprint(Date.is_valid("2025-01-15"))\nprint(Date.is_valid("2025/01/15"))',
            'expected': 'True\nFalse',
            'explain': '@staticmethod不需要self或cls参数，和普通函数一样，只是逻辑上属于类。适合工具方法。',
            'difficulty': 'intermediate',
        },
        {
            'id': 's16_04',
            'title': '用 abc 模块创建抽象类 Shape，有抽象方法 area()，创建 Rectangle 子类实现 area()',
            'desc': '用 abc 模块创建抽象类 Shape，有抽象方法 area()，创建 Rectangle 子类实现 area()',
            'diff': 'challenge',
            'kp': ['oop_abstract', 'print_basic'],
            'hint': 'from abc import ABC, abstractmethod',
            'template': 'from abc import ABC, abstractmethod\nclass Shape(ABC):\n    def area(self):\n        pass\nclass Rectangle(Shape):\n    def __init__(self, w, h):\n        pass\n    def area(self):\n        pass\nr =   # 填写值\nprint()  # 填写打印内容',
            'test_input': '',
            'answer': 'from abc import ABC, abstractmethod\n\nclass Shape(ABC):\n    @abstractmethod\n    def area(self):\n        pass\n\nclass Rectangle(Shape):\n    def __init__(self, w, h):\n        self.w = w\n        self.h = h\n    def area(self):\n        return self.w * self.h\n\nr = Rectangle(3, 4)\nprint(r.area())',
            'expected': '12',
            'explain': 'ABC+@abstractmethod定义抽象基类，子类必须实现所有抽象方法才能实例化，否则TypeError。',
            'difficulty': 'challenge',
        },
        {
            'id': 's16_05',
            'title': '创建 Car 类，组合 Engine 对象（有 hp 属性和 start() 方法），Car.start() 调用引擎启动',
            'desc': '创建 Car 类，组合 Engine 对象（有 hp 属性和 start() 方法），Car.start() 调用引擎启动',
            'diff': 'challenge',
            'kp': ['oop_composition', 'print_basic'],
            'hint': 'self.engine = Engine(hp)',
            'template': 'class Engine:\n    def __init__(self, hp):\n        pass\n    def start(self):\n        pass\nclass Car:\n    def __init__(self, brand, hp):\n        pass\n    def start(self):\n        pass\ncar =   # 填写值\nprint()  # 填写打印内容',
            'test_input': '',
            'answer': 'class Engine:\n    def __init__(self, hp):\n        self.hp = hp\n    def start(self):\n        return f"{self.hp}马力引擎启动！"\n\nclass Car:\n    def __init__(self, brand, hp):\n        self.brand = brand\n        self.engine = Engine(hp)\n    def start(self):\n        return f"{self.brand}：{self.engine.start()}"\n\ncar = Car("特斯拉", 300)\nprint(car.start())',
            'expected': '特斯拉：300马力引擎启动！',
            'explain': "组合：Car内部包含Engine对象，通过self.engine调用其方法。'有一个'关系优于'是一个'继承。",
            'difficulty': 'challenge',
        },
    ],
    17: [
        {
            'id': 's17_01',
            'title': '用 import math 导入，计算 16 的平方根并打印',
            'desc': '用 import math 导入，计算 16 的平方根并打印',
            'diff': 'basic',
            'kp': ['mod_import', 'print_basic'],
            'hint': 'import math; math.sqrt(16)',
            'template': 'import math\nprint()  # 填写打印内容',
            'test_input': '',
            'answer': 'import math\nprint(math.sqrt(16))',
            'expected': '4.0',
            'explain': 'import math导入整个模块，通过math.sqrt()调用。sqrt(16)=4.0。',
            'difficulty': 'basic',
        },
        {
            'id': 's17_02',
            'title': '用 from math import pi, sqrt 导入，打印 pi 的值和 sqrt(144) 的结果',
            'desc': '用 from math import pi, sqrt 导入，打印 pi 的值和 sqrt(144) 的结果',
            'diff': 'basic',
            'kp': ['mod_import', 'print_basic'],
            'hint': 'from math import pi, sqrt',
            'template': 'from math import pi, sqrt\nprint()  # 填写打印内容\nprint()  # 填写打印内容',
            'test_input': '',
            'answer': 'from math import pi, sqrt\nprint(pi)\nprint(sqrt(144))',
            'expected': '3.141592653589793\n12.0',
            'explain': 'from math import pi, sqrt只导入需要的名称，使用时无需math.前缀。',
            'difficulty': 'basic',
        },
        {
            'id': 's17_03',
            'title': "写一个模块 my_tools.py 的内容：包含 add(a,b) 函数和 if __name__=='__main__' 测试代码（把模块代码打印出来即可）",
            'desc': "写一个模块 my_tools.py 的内容：包含 add(a,b) 函数和 if __name__=='__main__' 测试代码（把模块代码打印出来即可）",
            'diff': 'basic',
            'kp': ['mod_name_main', 'print_basic'],
            'hint': '用 print 打印整个模块代码',
            'template': 'code =   # 填写值\n# ...\nif __name__ == "__main__":\n    pass\nprint()  # 填写打印内容\nprint()  # 填写打印内容',
            'test_input': '',
            'answer': 'code = """def add(a, b):\n    return a + b\n\nif __name__ == "__main__":\n    print(add(3, 5))"""\nprint(code)',
            'expected': 'def add(a, b):\n    return a + b\n\nif __name__ == "__main__":\n    print(add(3, 5))',
            'explain': "__name__=='__main__'确保模块被直接运行时才执行测试代码，被导入时不执行。",
            'difficulty': 'basic',
        },
        {
            'id': 's17_04',
            'title': '创建目录结构 my_package/__init__.py 和 my_package/math_tools.py（打印出目录结构描述即可）',
            'desc': '创建目录结构 my_package/__init__.py 和 my_package/math_tools.py（打印出目录结构描述即可）',
            'diff': 'intermediate',
            'kp': ['mod_package', 'print_basic'],
            'hint': '用 print 打印目录树',
            'template': 'print()  # 填写打印内容\nprint()  # 填写打印内容\nprint()  # 填写打印内容',
            'test_input': '',
            'answer': 'print("my_package/")\nprint("├── __init__.py")\nprint("└── math_tools.py")',
            'expected': 'my_package/\n├── __init__.py\n└── math_tools.py',
            'explain': '包是含__init__.py的目录。__init__.py可以为空，也可以定义包级变量或from .module import函数。',
            'difficulty': 'intermediate',
        },
        {
            'id': 's17_05',
            'title': '使用 os 模块获取当前工作目录并打印',
            'desc': '使用 os 模块获取当前工作目录并打印',
            'diff': 'intermediate',
            'kp': ['mod_stdlib', 'print_basic'],
            'hint': 'os.getcwd()',
            'template': 'import os\nprint()  # 填写打印内容',
            'test_input': '',
            'answer': 'import os\nprint(os.getcwd())',
            'expected': 'C:\\Users\\37845\\.qclaw\\workspace',
            'explain': 'os.getcwd()返回当前工作目录路径，等价于命令行pwd。',
            'difficulty': 'intermediate',
        },
        {
            'id': 's17_06',
            'title': '用 argparse 模块写一个命令行程序骨架，接受 --name 参数并打印问候语（代码中直接设默认值测试）',
            'desc': '用 argparse 模块写一个命令行程序骨架，接受 --name 参数并打印问候语（代码中直接设默认值测试）',
            'diff': 'challenge',
            'kp': ['mod_stdlib', 'print_basic'],
            'hint': "argparse.ArgumentParser(); parser.add_argument('--name')",
            'template': 'import argparse\nparser =   # 填写值\n# ...\nargs =   # 填写值\nprint()  # 填写打印内容',
            'test_input': '',
            'answer': 'import argparse\nparser = argparse.ArgumentParser()\nparser.add_argument("--name", default="世界")\nargs = parser.parse_args([])\nprint(f"你好，{args.name}！")',
            'expected': '你好，世界！',
            'explain': 'argparse模块处理命令行参数：add_argument定义参数，parse_args()解析。比sys.argv更强大。',
            'difficulty': 'challenge',
        },
    ],
    18: [
        {
            'id': 's18_01',
            'title': '写一个生成器函数 gen_squares(n)，yield 0到n-1的平方',
            'desc': '写一个生成器函数 gen_squares(n)，yield 0到n-1的平方',
            'diff': 'basic',
            'kp': ['gen_yield', 'print_basic'],
            'hint': 'for i in range(n): yield i**2',
            'template': 'def gen_squares(n):\n    pass\nprint()  # 填写打印内容',
            'test_input': '',
            'answer': 'def gen_squares(n):\n    for i in range(n):\n        yield i ** 2\n\nprint(list(gen_squares(5)))',
            'expected': '[0, 1, 4, 9, 16]',
            'explain': 'yield暂停函数并返回值，下次调用next()从暂停处继续。生成器惰性求值，省内存。',
            'difficulty': 'basic',
        },
        {
            'id': 's18_02',
            'title': '用生成器表达式生成 1~10 的立方，转为列表打印',
            'desc': '用生成器表达式生成 1~10 的立方，转为列表打印',
            'diff': 'basic',
            'kp': ['gen_expression', 'print_basic'],
            'hint': '(x**3 for x in range(1, 11))',
            'template': 'cubes =   # 填写值\nprint()  # 填写打印内容',
            'test_input': '',
            'answer': 'cubes = (x ** 3 for x in range(1, 11))\nprint(list(cubes))',
            'expected': '[1, 8, 27, 64, 125, 216, 343, 512, 729, 1000]',
            'explain': '生成器表达式(x**3 for x in range(1,11))，用list()转为列表。比列表推导式更省内存。',
            'difficulty': 'basic',
        },
        {
            'id': 's18_03',
            'title': '写一个装饰器 @shout，把函数返回值转为大写',
            'desc': '写一个装饰器 @shout，把函数返回值转为大写',
            'diff': 'intermediate',
            'kp': ['dec_basic', 'print_basic'],
            'hint': 'def shout(func): def wrapper(): return func().upper()...',
            'template': 'def shout(func):\n    pass\n    def wrapper():\n        pass\n# ...\n@shout\ndef greet():\n    pass\nprint()  # 填写打印内容',
            'test_input': '',
            'answer': 'def shout(func):\n    def wrapper():\n        result = func()\n        return result.upper()\n    return wrapper\n\n@shout\ndef greet():\n    return "hello world"\n\nprint(greet())',
            'expected': 'HELLO WORLD',
            'explain': '装饰器：wrapper拦截原函数调用，将返回值.upper()后返回。@shout语法糖等价于func=shout(func)。',
            'difficulty': 'intermediate',
        },
        {
            'id': 's18_04',
            'title': '写一个带参数的装饰器 @repeat(n)，让函数执行 n 次并返回结果列表',
            'desc': '写一个带参数的装饰器 @repeat(n)，让函数执行 n 次并返回结果列表',
            'diff': 'challenge',
            'kp': ['dec_args', 'print_basic'],
            'hint': 'def repeat(n): def decorator(func): def wrapper(*args, **kwargs): ...',
            'template': 'def repeat(n):\n    pass\n    def decorator(func):\n        pass\n        def wrapper(*args, **kwargs):\n            pass\n# ...\n# ...\n@repeat(3)\ndef greet(name):\n    pass\nprint()  # 填写打印内容',
            'test_input': '',
            'answer': 'def repeat(n):\n    def decorator(func):\n        def wrapper(*args, **kwargs):\n            return [func(*args, **kwargs) for _ in range(n)]\n        return wrapper\n    return decorator\n\n@repeat(3)\ndef greet(name):\n    return f"Hi {name}"\n\nprint(greet("张三"))',
            'expected': "['Hi 张三', 'Hi 张三', 'Hi 张三']",
            'explain': '带参数装饰器：外层函数接收参数n，返回真正的装饰器。wrapper循环n次执行被装饰函数。',
            'difficulty': 'challenge',
        },
        {
            'id': 's18_05',
            'title': '用 functools.wraps 修复装饰器，确保被装饰函数的 __name__ 不变',
            'desc': '用 functools.wraps 修复装饰器，确保被装饰函数的 __name__ 不变',
            'diff': 'challenge',
            'kp': ['dec_wraps', 'print_basic'],
            'hint': 'from functools import wraps; @wraps(func)',
            'template': 'from functools import wraps\ndef my_decorator(func):\n    pass\n    def wrapper(*args, **kwargs):\n        pass\n# ...\n@my_decorator\ndef my_function():\n    pass\nprint()  # 填写打印内容\nprint()  # 填写打印内容',
            'test_input': '',
            'answer': 'from functools import wraps\n\ndef my_decorator(func):\n    @wraps(func)\n    def wrapper(*args, **kwargs):\n        return func(*args, **kwargs)\n    return wrapper\n\n@my_decorator\ndef my_function():\n    """This is my function"""\n    pass\n\nprint(my_function.__name__)\nprint(my_function.__doc__)',
            'expected': 'my_function\nThis is my function',
            'explain': '@functools.wraps(func)保留原函数的__name__、__doc__等元信息。否则装饰后函数名变成wrapper。',
            'difficulty': 'challenge',
        },
        {
            'id': 's18_06',
            'title': '用 contextlib.contextmanager 写一个 timer 上下文管理器，打印代码块执行时间',
            'desc': '用 contextlib.contextmanager 写一个 timer 上下文管理器，打印代码块执行时间',
            'diff': 'challenge',
            'kp': ['ctx_manager', 'print_basic'],
            'hint': 'from contextlib import contextmanager; yield;',
            'template': 'from contextlib import contextmanager\nimport time\n@contextmanager\ndef timer():\n    pass\nwith timer():\n    pass\n# ...',
            'test_input': '',
            'answer': 'from contextlib import contextmanager\nimport time\n\n@contextmanager\ndef timer():\n    start = time.time()\n    yield\n    elapsed = time.time() - start\n    print(f"耗时{elapsed:.4f}秒")\n\nwith timer():\n    sum(range(100000))',
            'expected': '耗时0.0020秒',
            'explain': 'contextlib.contextmanager将生成器变为上下文管理器。yield前是__enter__，yield后是__exit__。',
            'difficulty': 'challenge',
        },
    ],
}
