# EXERCISES_8_13 - v5.0 unified format

EXERCISES_8_13 = {
    8: [
        {
            'id': 's8_01',
            'title': '创建字典 student = {"name": "张三", "score": 92}，打印 name 的值',
            'desc': '创建字典 student = {"name": "张三", "score": 92}，打印 name 的值',
            'diff': 'basic',
            'kp': ['dict_create', 'dict_access', 'print_basic'],
            'hint': 'student["name"]',
            'template': 'student =   # 填写值\nprint()  # 填写打印内容',
            'test_input': '',
            'answer': 'student = {"name": "张三", "score": 92}\nprint(student["name"])',
            'expected': '张三',
            'explain': "字典用方括号student['name']访问值。键不存在会KeyError，可用get()安全访问。",
            'difficulty': 'basic',
        },
        {
            'id': 's8_02',
            'title': '用 get 方法安全访问字典，键不存在返回 "无"',
            'desc': '用 get 方法安全访问字典，键不存在返回 "无"',
            'diff': 'basic',
            'kp': ['dict_methods', 'print_basic'],
            'hint': 'dict.get(key, default)',
            'template': 'person =   # 填写值\nprint()  # 填写打印内容\nprint()  # 填写打印内容',
            'test_input': '',
            'answer': 'person = {"name": "张三", "age": 25}\nprint(person.get("name", "无"))\nprint(person.get("phone", "无"))',
            'expected': '张三\n无',
            'explain': 'dict.get(key, default)：键存在返回值，不存在返回默认值。比try-except或if key in dict更简洁。',
            'difficulty': 'basic',
        },
        {
            'id': 's8_03',
            'title': '遍历字典 {"语文":90, "数学":85, "英语":92}，打印每科成绩',
            'desc': '遍历字典 {"语文":90, "数学":85, "英语":92}，打印每科成绩',
            'diff': 'basic',
            'kp': ['dict_methods', 'print_basic'],
            'hint': 'for k, v in dict.items():',
            'template': 'scores =   # 填写值\nfor subject, score in scores.items():\n    pass\nprint()  # 填写打印内容',
            'test_input': '',
            'answer': 'scores = {"语文": 90, "数学": 85, "英语": 92}\nfor subject, score in scores.items():\n    print(f"{subject}: {score}")',
            'expected': '语文: 90\n数学: 85\n英语: 92',
            'explain': 'dict.items()返回(key, value)对，遍历时同时获得键和值。.keys()只取键，.values()只取值。',
            'difficulty': 'basic',
        },
        {
            'id': 's8_04',
            'title': '统计字符串 "hello world" 中每个字符出现的次数，用字典打印',
            'desc': '统计字符串 "hello world" 中每个字符出现的次数，用字典打印',
            'diff': 'intermediate',
            'kp': ['dict_create', 'dict_methods', 'list_iter'],
            'hint': '遍历字符串，用字典计数',
            'template': 'text =   # 填写值\ncounts =   # 填写值\nfor ch in text:\n    pass\n# ...\nprint()  # 填写打印内容',
            'test_input': '',
            'answer': 'text = "hello world"\ncounts = {}\nfor ch in text:\n    counts[ch] = counts.get(ch, 0) + 1\nprint(counts)',
            'expected': "{'h': 1, 'e': 1, 'l': 3, 'o': 2, ' ': 1, 'w': 1, 'r': 1, 'd': 1}",
            'explain': '字符统计：遍历字符串，d[ch]=d.get(ch,0)+1。空格也会被统计。collections.Counter更快捷。',
            'difficulty': 'intermediate',
        },
        {
            'id': 's8_05',
            'title': '合并两个字典：a={"x":1,"y":2} 和 b={"y":3,"z":4}，b 的值覆盖 a 的同名键',
            'desc': '合并两个字典：a={"x":1,"y":2} 和 b={"y":3,"z":4}，b 的值覆盖 a 的同名键',
            'diff': 'challenge',
            'kp': ['dict_update', 'print_basic'],
            'hint': 'a.copy() 然后 update(b)，或 {**a, **b}',
            'template': 'a =   # 填写值\nb =   # 填写值\nmerged =   # 填写值\nprint()  # 填写打印内容',
            'test_input': '',
            'answer': 'a = {"x": 1, "y": 2}\nb = {"y": 3, "z": 4}\nmerged = {**a, **b}\nprint(merged)',
            'expected': "{'x': 1, 'y': 3, 'z': 4}",
            'explain': '字典合并：{**a, **b}解包合并，b的键覆盖a中同名键。y=3覆盖了a中的y=2。',
            'difficulty': 'challenge',
        },
        {
            'id': 's8_06',
            'title': '用字典推导式把列表 ["apple","banana","cherry"] 转为 {水果名: 长度} 的字典并打印',
            'desc': '用字典推导式把列表 ["apple","banana","cherry"] 转为 {水果名: 长度} 的字典并打印',
            'diff': 'intermediate',
            'kp': ['dict_create', 'list_iter', 'print_basic'],
            'hint': '{k: len(k) for k in lst}',
            'template': 'fruits =   # 填写值\nresult =   # 填写值\nprint()  # 填写打印内容',
            'test_input': '',
            'answer': 'fruits = ["apple", "banana", "cherry"]\nresult = {f: len(f) for f in fruits}\nprint(result)',
            'expected': "{'apple': 5, 'banana': 6, 'cherry': 6}",
            'explain': '字典推导式：{k: len(k) for k in lst}，key是水果名，value是字符串长度。',
            'difficulty': 'intermediate',
        },
    ],
    9: [
        {
            'id': 's9_01',
            'title': '从列表 [1, 1, 2, 2, 3, 3, 3] 创建集合并打印（去重）',
            'desc': '从列表 [1, 1, 2, 2, 3, 3, 3] 创建集合并打印（去重）',
            'diff': 'basic',
            'kp': ['set_create', 'print_basic'],
            'hint': 'set(列表)',
            'template': 'nums =   # 填写值\nunique =   # 填写值\nprint()  # 填写打印内容',
            'test_input': '',
            'answer': 'nums = [1, 1, 2, 2, 3, 3, 3]\nunique = set(nums)\nprint(unique)',
            'expected': '{1, 2, 3}',
            'explain': 'set()去重：集合中元素唯一。{1,1,2,2,3,3,3}→{1,2,3}，自动去除重复元素。',
            'difficulty': 'basic',
        },
        {
            'id': 's9_02',
            'title': 'a={1,2,3}, b={2,3,4}，分别打印交集和并集',
            'desc': 'a={1,2,3}, b={2,3,4}，分别打印交集和并集',
            'diff': 'basic',
            'kp': ['set_ops', 'print_basic'],
            'hint': 'a & b 交集，a | b 并集',
            'template': 'a =   # 填写值\nb =   # 填写值\nprint()  # 填写打印内容\nprint()  # 填写打印内容',
            'test_input': '',
            'answer': 'a = {1, 2, 3}\nb = {2, 3, 4}\nprint(a & b)\nprint(a | b)',
            'expected': '{2, 3}\n{1, 2, 3, 4}',
            'explain': '交集&(共有的元素)，并集|(所有元素合在一起去重)。{1,2,3}&{2,3,4}={2,3}。',
            'difficulty': 'basic',
        },
        {
            'id': 's9_03',
            'title': '检查 5 是否在集合 {1, 3, 5, 7, 9} 中，打印结果',
            'desc': '检查 5 是否在集合 {1, 3, 5, 7, 9} 中，打印结果',
            'diff': 'basic',
            'kp': ['set_methods', 'print_basic'],
            'hint': '5 in s',
            'template': 's =   # 填写值\nprint()  # 填写打印内容',
            'test_input': '',
            'answer': 's = {1, 3, 5, 7, 9}\nprint(5 in s)',
            'expected': 'True',
            'explain': 'in运算符判断元素是否在集合中，时间复杂度O(1)，比列表的O(n)快得多。',
            'difficulty': 'basic',
        },
        {
            'id': 's9_04',
            'title': '求两个列表 [1,2,3,4,5] 和 [4,5,6,7,8] 的公共元素（交集），打印结果',
            'desc': '求两个列表 [1,2,3,4,5] 和 [4,5,6,7,8] 的公共元素（交集），打印结果',
            'diff': 'intermediate',
            'kp': ['set_ops', 'set_create', 'print_basic'],
            'hint': 'set(a) & set(b)',
            'template': 'a =   # 填写值\nb =   # 填写值\ncommon =   # 填写值\nprint()  # 填写打印内容',
            'test_input': '',
            'answer': 'a = [1, 2, 3, 4, 5]\nb = [4, 5, 6, 7, 8]\ncommon = set(a) & set(b)\nprint(common)',
            'expected': '{4, 5}',
            'explain': '集合交集：set(list1)&set(list2)，先将列表转集合再做运算。',
            'difficulty': 'intermediate',
        },
        {
            'id': 's9_05',
            'title': '用集合判断两个字符串 "abcdef" 和 "defghi" 是否有公共字符，打印 True 或 False',
            'desc': '用集合判断两个字符串 "abcdef" 和 "defghi" 是否有公共字符，打印 True 或 False',
            'diff': 'intermediate',
            'kp': ['set_ops', 'set_create', 'print_basic'],
            'hint': 'bool(set(s1) & set(s2))',
            'template': 's1 =   # 填写值\ns2 =   # 填写值\nprint()  # 填写打印内容',
            'test_input': '',
            'answer': 's1 = "abcdef"\ns2 = "defghi"\nprint(bool(set(s1) & set(s2)))',
            'expected': 'True',
            'explain': 'isdisjoint()判断两个集合是否没有公共元素。True表示没有交集，False表示有交集。',
            'difficulty': 'intermediate',
        },
        {
            'id': 's9_06',
            'title': '用集合找出列表 [3,1,4,1,5,9,2,6,5,3] 中所有不重复的偶数，排序后打印',
            'desc': '用集合找出列表 [3,1,4,1,5,9,2,6,5,3] 中所有不重复的偶数，排序后打印',
            'diff': 'challenge',
            'kp': ['set_create', 'list_iter', 'print_basic'],
            'hint': '集合推导式 {x for x in lst if x%2==0}，然后 sorted()',
            'template': 'nums =   # 填写值\neven_unique =   # 填写值\nprint()  # 填写打印内容',
            'test_input': '',
            'answer': 'nums = [3, 1, 4, 1, 5, 9, 2, 6, 5, 3]\neven_unique = sorted({x for x in nums if x % 2 == 0})\nprint(even_unique)',
            'expected': '[2, 4, 6]',
            'explain': '集合推导式+条件过滤：{x for x in lst if x%2==0}，再sorted()排序输出列表。',
            'difficulty': 'challenge',
        },
        {
            'id': 's9_07',
            'title': 'a={1,2,3,4,5}, b={3,4,5,6,7}，求 a-b（只在a中不在b中）和 b-a（只在b中不在a中），分别打印',
            'desc': 'a={1,2,3,4,5}, b={3,4,5,6,7}，求 a-b（只在a中不在b中）和 b-a（只在b中不在a中），分别打印',
            'diff': 'intermediate',
            'kp': ['set_ops', 'print_basic'],
            'hint': 'a - b 差集',
            'template': 'a =   # 填写值\nb =   # 填写值\nprint()  # 填写打印内容\nprint()  # 填写打印内容',
            'test_input': '',
            'answer': 'a = {1, 2, 3, 4, 5}\nb = {3, 4, 5, 6, 7}\nprint(a - b)\nprint(b - a)',
            'expected': '{1, 2}\n{6, 7}',
            'explain': '差集-：a-b表示在a中但不在b中的元素。a-b={1,2}，b-a={6,7}。',
            'difficulty': 'intermediate',
        },
    ],
    10: [
        {
            'id': 's10_01',
            'title': '将字符串 "hello world" 转为 "Hello World"（每个单词首字母大写）',
            'desc': '将字符串 "hello world" 转为 "Hello World"（每个单词首字母大写）',
            'diff': 'basic',
            'kp': ['str_methods', 'list_iter'],
            'hint': 'split 后 title() 再 join',
            'template': 'text =   # 填写值\nwords =   # 填写值\nresult =   # 填写值\nprint()  # 填写打印内容',
            'test_input': '',
            'answer': 'text = "hello world"\nwords = text.split()\nresult = " ".join(w.title() for w in words)\nprint(result)',
            'expected': 'Hello World',
            'explain': '.title()将每个单词首字母大写。等价于手动split→capitalize→join，但更简洁。',
            'difficulty': 'basic',
        },
        {
            'id': 's10_02',
            'title': '统计字符串 "abc123" 中有多少个数字字符',
            'desc': '统计字符串 "abc123" 中有多少个数字字符',
            'diff': 'basic',
            'kp': ['str_check', 'list_iter'],
            'hint': '用 isdigit() 判断每个字符',
            'template': 's =   # 填写值\ncount =   # 填写值\nfor ch in s:\n    pass\n    if ch.isdigit():\n        pass\n# ...\nprint()  # 填写打印内容',
            'test_input': '',
            'answer': 's = "abc123"\ncount = 0\nfor ch in s:\n    if ch.isdigit():\n        count += 1\nprint(count)',
            'expected': '3',
            'explain': 'str.isdigit()判断单个字符是否为数字。sum(1 for c in s if c.isdigit())统计数字字符数。',
            'difficulty': 'basic',
        },
        {
            'id': 's10_03',
            'title': '用 f-string 将 1234.5 显示为 "1,234.50"',
            'desc': '用 f-string 将 1234.5 显示为 "1,234.50"',
            'diff': 'intermediate',
            'kp': ['str_format', 'print_basic'],
            'hint': 'f"{num:,.2f}"',
            'template': 'amount =   # 填写值\nresult =   # 填写值\nprint()  # 填写打印内容',
            'test_input': '',
            'answer': 'amount = 1234.5\nresult = f"{amount:,.2f}"\nprint(result)',
            'expected': '1,234.50',
            'explain': 'f-string格式化：{value:,.2f}中,添加千位分隔符，.2f保留2位小数。',
            'difficulty': 'intermediate',
        },
        {
            'id': 's10_04',
            'title': '检查字符串 "racecar" 是否是回文（正反读一样），打印 True 或 False',
            'desc': '检查字符串 "racecar" 是否是回文（正反读一样），打印 True 或 False',
            'diff': 'intermediate',
            'kp': ['str_methods', 'op_compare'],
            'hint': 's == s[::-1]',
            'template': 's =   # 填写值\nprint()  # 填写打印内容',
            'test_input': '',
            'answer': 's = "racecar"\nprint(s == s[::-1])',
            'expected': 'True',
            'explain': "回文判断：s==s[::-1]，正序等于逆序即为回文。'racecar'[::-1]='racecar'。",
            'difficulty': 'intermediate',
        },
        {
            'id': 's10_05',
            'title': '把字符串 "hello, world, python" 按逗号分割成列表，去掉每项的空格，再转为大写，打印结果',
            'desc': '把字符串 "hello, world, python" 按逗号分割成列表，去掉每项的空格，再转为大写，打印结果',
            'diff': 'challenge',
            'kp': ['str_methods', 'list_comprehension'],
            'hint': "split(',') + 列表推导式 strip().upper()",
            'template': 'text =   # 填写值\nresult =   # 填写值\nprint()  # 填写打印内容',
            'test_input': '',
            'answer': 'text = "hello, world, python"\nresult = [w.strip().upper() for w in text.split(",")]\nprint(result)',
            'expected': "['HELLO', 'WORLD', 'PYTHON']",
            'explain': "split(',')按逗号分割→列表推导式strip().upper()去空格转大写。链式操作一行搞定。",
            'difficulty': 'challenge',
        },
        {
            'id': 's10_06',
            'title': '替换字符串 "I love Java" 中的 "Java" 为 "Python"，打印结果',
            'desc': '替换字符串 "I love Java" 中的 "Java" 为 "Python"，打印结果',
            'diff': 'basic',
            'kp': ['str_methods', 'print_basic'],
            'hint': 's.replace(old, new)',
            'template': 's =   # 填写值\nresult =   # 填写值\nprint()  # 填写打印内容',
            'test_input': '',
            'answer': 's = "I love Java"\nresult = s.replace("Java", "Python")\nprint(result)',
            'expected': 'I love Python',
            'explain': ".replace(old, new)替换所有匹配项。'I love Java'.replace('Java','Python')→'I love Python'。",
            'difficulty': 'basic',
        },
    ],
    11: [
        {
            'id': 's11_01',
            'title': '将列表 ["苹果","香蕉","橙子"] 写入文件 fruits.txt（每行一个），然后打印"写入完成"',
            'desc': '将列表 ["苹果","香蕉","橙子"] 写入文件 fruits.txt（每行一个），然后打印"写入完成"',
            'diff': 'basic',
            'kp': ['file_open', 'file_write', 'file_context', 'list_iter'],
            'hint': "with open(...) as f: for item in lst: f.write(item + '\\n')",
            'template': 'fruits =   # 填写值\nwith open("fruits.txt", "w", encoding="utf-8") as f:\n    pass\n    for fruit in fruits:\n        pass\n# ...\nprint()  # 填写打印内容',
            'test_input': '',
            'answer': 'fruits = ["苹果", "香蕉", "橙子"]\nwith open("fruits.txt", "w", encoding="utf-8") as f:\n    for fruit in fruits:\n        f.write(fruit + "\\n")\nprint("写入完成")',
            'expected': '写入完成',
            'explain': "with open()自动管理文件关闭。'w'模式写入，write()写字符串，每行末尾加\\n。",
            'difficulty': 'basic',
        },
        {
            'id': 's11_02',
            'title': '读取 fruits.txt 并打印每一行（去掉换行符），如果文件不存在打印"文件不存在"',
            'desc': '读取 fruits.txt 并打印每一行（去掉换行符），如果文件不存在打印"文件不存在"',
            'diff': 'intermediate',
            'kp': ['file_open', 'file_read', 'file_context', 'try_except'],
            'hint': 'try: ... except FileNotFoundError: ...',
            'template': '# ...\n    with open("fruits.txt", "r", encoding="utf-8") as f:\n        pass\n        for line in f:\n            pass\nprint()  # 填写打印内容\n# ...\nprint()  # 填写打印内容',
            'test_input': '',
            'answer': 'try:\n    with open("fruits.txt", "r", encoding="utf-8") as f:\n        for line in f:\n            print(line.strip())\nexcept FileNotFoundError:\n    print("文件不存在")',
            'expected': '苹果\n香蕉\n橙子',
            'explain': 'FileNotFoundError处理文件不存在的情况。strip()去掉行末换行符。readlines()读所有行。',
            'difficulty': 'intermediate',
        },
        {
            'id': 's11_03',
            'title': '向 fruits.txt 追加一行 "葡萄"，然后读取并打印整个文件内容',
            'desc': '向 fruits.txt 追加一行 "葡萄"，然后读取并打印整个文件内容',
            'diff': 'intermediate',
            'kp': ['file_write', 'file_read', 'file_context'],
            'hint': 'open(..., "a") 追加模式',
            'template': 'with open("fruits.txt", "a", encoding="utf-8") as f:\n    pass\n# ...\nwith open("fruits.txt", "r", encoding="utf-8") as f:\n    pass\nprint()  # 填写打印内容',
            'test_input': '',
            'answer': 'with open("fruits.txt", "a", encoding="utf-8") as f:\n    f.write("葡萄\\n")\n\nwith open("fruits.txt", "r", encoding="utf-8") as f:\n    print(f.read().strip())',
            'expected': '苹果\n香蕉\n橙子\n葡萄\n葡萄',
            'explain': "'a'模式追加写入，不会覆盖原内容。追加后用'r'模式读取全部内容。",
            'difficulty': 'intermediate',
        },
        {
            'id': 's11_04',
            'title': '统计文件 fruits.txt 有多少行，打印行数（文件不存在则打印 0）',
            'desc': '统计文件 fruits.txt 有多少行，打印行数（文件不存在则打印 0）',
            'diff': 'intermediate',
            'kp': ['file_read', 'file_context', 'try_except', 'print_basic'],
            'hint': 'try: sum(1 for line in f) except: 0',
            'template': '# ...\n    with open("fruits.txt", "r", encoding="utf-8") as f:\n        pass\nlines =   # 填写值\nprint()  # 填写打印内容\n# ...\nprint()  # 填写打印内容',
            'test_input': '',
            'answer': 'try:\n    with open("fruits.txt", "r", encoding="utf-8") as f:\n        lines = sum(1 for line in f)\n    print(lines)\nexcept FileNotFoundError:\n    print(0)',
            'expected': '5',
            'explain': 'len(f.readlines())统计行数。文件不存在时except捕获异常返回0。',
            'difficulty': 'intermediate',
        },
        {
            'id': 's11_05',
            'title': '写一个函数 count_char(filename, ch)，统计文件中某字符出现次数，返回数字。对 fruits.txt 统计换行符次数并打印',
            'desc': '写一个函数 count_char(filename, ch)，统计文件中某字符出现次数，返回数字。对 fruits.txt 统计换行符次数并打印',
            'diff': 'challenge',
            'kp': ['func_def', 'func_return', 'file_read', 'file_context'],
            'hint': 'f.read().count(ch)',
            'template': 'def count_char(filename, ch):\n    pass\nprint()  # 填写打印内容',
            'test_input': '',
            'answer': 'def count_char(filename, ch):\n    with open(filename, "r", encoding="utf-8") as f:\n        return f.read().count(ch)\n\nprint(count_char("fruits.txt", "\\n"))',
            'expected': '5',
            'explain': 'f.read().count(ch)统计字符出现次数。count()是字符串方法，比循环计数更高效。',
            'difficulty': 'challenge',
        },
    ],
    12: [
        {
            'id': 's12_01',
            'title': '写一个安全除法函数 safe_divide(a, b)，除数为零时返回 None 并打印提示',
            'desc': '写一个安全除法函数 safe_divide(a, b)，除数为零时返回 None 并打印提示',
            'diff': 'basic',
            'kp': ['func_def', 'try_except', 'exception_types'],
            'hint': 'try: return a/b except ZeroDivisionError: ...',
            'template': 'def safe_divide(a, b):\n    pass\nprint()  # 填写打印内容\nprint()  # 填写打印内容',
            'test_input': '',
            'answer': 'def safe_divide(a, b):\n    try:\n        return a / b\n    except ZeroDivisionError:\n        print("错误：不能除以零")\n        return None\n\nprint(safe_divide(10, 3))\nprint(safe_divide(10, 0))',
            'expected': '3.3333333333333335\n错误：不能除以零\nNone',
            'explain': 'try-except捕获ZeroDivisionError，除数为0时执行except分支，返回None并打印提示。',
            'difficulty': 'basic',
        },
        {
            'id': 's12_02',
            'title': "写一个循环，让用户输入整数，输入无效时提示重新输入，输入 'q' 退出",
            'desc': '（模拟输入：先输 abc 再输 42 再输 q）',
            'diff': 'intermediate',
            'kp': ['while_loop', 'try_except', 'break_continue'],
            'hint': 'while True: try: int(input()) except ValueError: ...',
            'template': 'while True:\n    pass\nuser_input =   # 填写值\n    if user_input == "q":\n        pass\n# ...\n# ...\nnum =   # 填写值\nprint()  # 填写打印内容\n# ...\nprint()  # 填写打印内容',
            'test_input': '',
            'answer': 'while True:\n    user_input = input("请输入整数（q退出）：")\n    if user_input == "q":\n        break\n    try:\n        num = int(user_input)\n        print(f"你输入了：{num}")\n    except ValueError:\n        print("无效输入，请重新输入！")',
            'expected': '',
            'explain': 'ValueError处理非数字输入，int()转换失败时触发。while True+break构成输入循环。',
            'difficulty': 'intermediate',
        },
        {
            'id': 's12_03',
            'title': '写一个函数 validate_age(age_str)，验证年龄在 0-150 之间，无效时 raise ValueError',
            'desc': '然后调用并捕获异常',
            'diff': 'intermediate',
            'kp': ['func_def', 'raise_error', 'try_except'],
            'hint': 'raise ValueError("...")',
            'template': 'def validate_age(age_str):\n    pass\n# ...\nprint()  # 填写打印内容\nprint()  # 填写打印内容\n# ...\nprint()  # 填写打印内容',
            'test_input': '',
            'answer': 'def validate_age(age_str):\n    age = int(age_str)\n    if age < 0 or age > 150:\n        raise ValueError("年龄必须在0-150之间")\n    return age\n\ntry:\n    print(validate_age("25"))\n    print(validate_age("200"))\nexcept ValueError as e:\n    print(f"错误：{e}")',
            'expected': '25\n错误：年龄必须在0-150之间',
            'explain': "raise ValueError('消息')主动抛出异常。调用方需要try-except捕获。",
            'difficulty': 'intermediate',
        },
        {
            'id': 's12_04',
            'title': '读取一个可能不存在的文件 data.txt，用 try-except-finally 打印"处理完成"',
            'desc': '读取一个可能不存在的文件 data.txt，用 try-except-finally 打印"处理完成"',
            'diff': 'challenge',
            'kp': ['try_except', 'file_open', 'exception_types'],
            'hint': 'try: open(...) except FileNotFoundError: ... finally: print(...)',
            'template': '# ...\n    with open("data.txt", "r", encoding="utf-8") as f:\n        pass\ncontent =   # 填写值\n# ...\nprint()  # 填写打印内容\n# ...\nprint()  # 填写打印内容',
            'test_input': '',
            'answer': 'try:\n    with open("data.txt", "r", encoding="utf-8") as f:\n        content = f.read()\nexcept FileNotFoundError:\n    print("文件不存在")\nfinally:\n    print("处理完成")',
            'expected': '文件不存在\n处理完成',
            'explain': 'try-except-finally三段式：try尝试操作，except处理异常，finally无论成败都执行。',
            'difficulty': 'challenge',
        },
        {
            'id': 's12_05',
            'title': '写一个函数 safe_index(lst, i)，安全访问列表索引，越界时返回 None 而不报错',
            'desc': '调用 print(safe_index([1,2,3], 5))',
            'diff': 'basic',
            'kp': ['func_def', 'try_except', 'exception_types'],
            'hint': 'try: return lst[i] except IndexError: return None',
            'template': 'def safe_index(lst, i):\n    pass\nprint()  # 填写打印内容',
            'test_input': '',
            'answer': 'def safe_index(lst, i):\n    try:\n        return lst[i]\n    except IndexError:\n        return None\n\nprint(safe_index([1, 2, 3], 5))',
            'expected': 'None',
            'explain': 'IndexError捕获越界访问。安全函数返回None而不是崩溃，这是防御性编程的思路。',
            'difficulty': 'basic',
        },
    ],
    13: [
        {
            'id': 's13_01',
            'title': '导入 datetime 模块，打印今天的日期',
            'desc': '导入 datetime 模块，打印今天的日期',
            'diff': 'basic',
            'kp': ['import_module', 'datetime_mod'],
            'hint': 'import datetime; datetime.date.today()',
            'template': 'import datetime\ntoday =   # 填写值\nprint()  # 填写打印内容',
            'test_input': '',
            'answer': 'import datetime\ntoday = datetime.date.today()\nprint(f"今天是：{today}")',
            'expected': '今天是：2026-05-03',
            'explain': 'datetime.date.today()获取当天日期。需要from datetime import date或import datetime。',
            'difficulty': 'basic',
        },
        {
            'id': 's13_02',
            'title': '用 json 模块将字典保存到文件 data.json，再读取出来打印',
            'desc': '用 json 模块将字典保存到文件 data.json，再读取出来打印',
            'diff': 'intermediate',
            'kp': ['import_module', 'json_io', 'file_context'],
            'hint': 'json.dump() 和 json.load()',
            'template': 'import json\ndata =   # 填写值\nwith open("data.json", "w", encoding="utf-8") as f:\n    pass\n# ...\nwith open("data.json", "r", encoding="utf-8") as f:\n    pass\nloaded =   # 填写值\nprint()  # 填写打印内容',
            'test_input': '',
            'answer': 'import json\ndata = {"name": "张三", "age": 25}\nwith open("data.json", "w", encoding="utf-8") as f:\n    json.dump(data, f, ensure_ascii=False, indent=2)\nwith open("data.json", "r", encoding="utf-8") as f:\n    loaded = json.load(f)\nprint(loaded)',
            'expected': "{'name': '张三', 'age': 25}",
            'explain': 'json.dumps()序列化(Python→JSON字符串)，json.loads()反序列化(JSON→Python对象)。',
            'difficulty': 'intermediate',
        },
        {
            'id': 's13_03',
            'title': '用 datetime 计算 100 天后是哪一天，打印结果',
            'desc': '用 datetime 计算 100 天后是哪一天，打印结果',
            'diff': 'intermediate',
            'kp': ['import_module', 'datetime_mod'],
            'hint': 'today + datetime.timedelta(days=100)',
            'template': 'import datetime\ntoday =   # 填写值\nfuture =   # 填写值\nprint()  # 填写打印内容',
            'test_input': '',
            'answer': 'import datetime\ntoday = datetime.date.today()\nfuture = today + datetime.timedelta(days=100)\nprint(f"100天后是：{future}")',
            'expected': '100天后是：2026-08-11',
            'explain': 'timedelta做日期运算：today+timedelta(days=100)得到100天后的日期。',
            'difficulty': 'intermediate',
        },
        {
            'id': 's13_04',
            'title': '写一个函数 save_and_load(data, filename)，将数据保存为 JSON 再读回，验证数据一致则打印 True',
            'desc': '写一个函数 save_and_load(data, filename)，将数据保存为 JSON 再读回，验证数据一致则打印 True',
            'diff': 'challenge',
            'kp': ['import_module', 'json_io', 'file_context', 'func_def'],
            'hint': 'json.dump + json.load + 比较字典',
            'template': 'import json\ndef save_and_load(data, filename):\n    pass\nprint()  # 填写打印内容',
            'test_input': '',
            'answer': 'import json\n\ndef save_and_load(data, filename):\n    with open(filename, "w", encoding="utf-8") as f:\n        json.dump(data, f, ensure_ascii=False)\n    with open(filename, "r", encoding="utf-8") as f:\n        loaded = json.load(f)\n    return loaded == data\n\nprint(save_and_load({"x": 1, "y": [2, 3]}, "test.json"))',
            'expected': 'True',
            'explain': "组合json+文件操作：json.dump(data, f)直接写入文件，json.load(f)直接读取。注意'w'写入'r'读取。",
            'difficulty': 'challenge',
        },
        {
            'id': 's13_05',
            'title': '用 random 模块生成 5 个 1-100 的随机整数并打印',
            'desc': '用 random 模块生成 5 个 1-100 的随机整数并打印',
            'diff': 'basic',
            'kp': ['import_module', 'for_loop', 'print_basic'],
            'hint': 'import random; random.randint(1, 100)',
            'template': 'import random\nfor _ in range(5):\n    pass\nprint()  # 填写打印内容',
            'test_input': '',
            'answer': 'import random\nfor _ in range(5):\n    print(random.randint(1, 100))',
            'expected': '33\n39\n69\n61\n7',
            'explain': 'random.randint(1,100)生成1到100的随机整数(含两端)。列表推导式生成5个。',
            'difficulty': 'basic',
        },
    ],
}
