"""练习题数据 - 阶段19~21 — v5.0 第三篇：工程基础"""
from typing import List, Dict

EXERCISES_19_21 = {
    19: [
        {
            'id': 'db_sqlite_crud',
            'title': 'SQLite 增删改查',
            'desc': '创建表、插入数据、查询结果',
            'diff': 'basic',
            'kp': ['db_sqlite'],
            'template': 'import sqlite3\n\nconn = sqlite3.connect(":memory:")\ncursor = conn.cursor()\n\ncursor.execute("CREATE TABLE students (id INTEGER PRIMARY KEY, name TEXT, age INTEGER)")\n\ncursor.execute("____________ INTO students (name, age) VALUES (?, ?)", ("Alice", 20))\nconn.commit()\n\ncursor.execute("SELECT * FROM students WHERE ____________ > 18")\nfor row in cursor.fetchall():\n    print(row)',
            'test_input': '',
            'answer': 'import sqlite3\n\nconn = sqlite3.connect(":memory:")\ncursor = conn.cursor()\n\ncursor.execute("CREATE TABLE students (id INTEGER PRIMARY KEY, name TEXT, age INTEGER)")\n\ncursor.execute("INSERT INTO students (name, age) VALUES (?, ?)", ("Alice", 20))\nconn.commit()\n\ncursor.execute("SELECT * FROM students WHERE age > 18")\nfor row in cursor.fetchall():\n    print(row)',
            'expected': "(1, 'Alice', 20)",
            'explain': "SQLite内置数据库，connect(':memory:')创建内存数据库。cursor.execute()执行SQL，commit()提交事务。",
            'difficulty': 'basic',
        },
        {
            'id': 'db_sqlalchemy_model',
            'title': 'SQLAlchemy 模型定义',
            'desc': '定义一个 Book 模型并创建表',
            'diff': 'basic',
            'kp': ['db_sqlalchemy'],
            'template': 'from sqlalchemy import Column, Integer, String\nfrom sqlalchemy.orm import declarative_base\n\nBase = declarative_base()\n\nclass Book(Base):\n    __tablename__ = "books"\n    id = Column(Integer, ____________=True)\n    title = Column(String(100))\n    author = Column(String(50))\n\n    def __repr__(self):\n        return f"<Book {{self.title}}>"\n\nprint(Book.__tablename__)',
            'test_input': '',
            'answer': 'from sqlalchemy import Column, Integer, String\nfrom sqlalchemy.orm import declarative_base\n\nBase = declarative_base()\n\nclass Book(Base):\n    __tablename__ = "books"\n    id = Column(Integer, primary_key=True)\n    title = Column(String(100))\n    author = Column(String(50))\n\n    def __repr__(self):\n        return f"<Book {{self.title}}>"\n\nprint(Book.__tablename__)',
            'expected': 'books',
            'explain': 'SQLAlchemy ORM：Base声明基类，Column定义字段类型。Integer/String/Float映射到数据库列。',
            'difficulty': 'basic',
        },
        {
            'id': 'db_sqlalchemy_query',
            'title': 'SQLAlchemy 查询',
            'desc': '用 Session 添加和查询数据',
            'diff': 'intermediate',
            'kp': ['db_sqlalchemy'],
            'template': 'from sqlalchemy import create_engine, Column, Integer, String\nfrom sqlalchemy.orm import declarative_base, Session\n\nBase = declarative_base()\n\nclass User(Base):\n    __tablename__ = "users"\n    id = Column(Integer, primary_key=True)\n    name = Column(String(50))\n\nengine = create_engine("sqlite:///:memory:")\nBase.metadata.create_all(engine)\n\nsession = ____________(engine)\nsession.add(User(name="Alice"))\nsession.____________()\n\nusers = session.query(User).filter(User.name == "Alice").all()\nprint(users[0].name)\nsession.close()',
            'test_input': '',
            'answer': 'from sqlalchemy import create_engine, Column, Integer, String\nfrom sqlalchemy.orm import declarative_base, Session\n\nBase = declarative_base()\n\nclass User(Base):\n    __tablename__ = "users"\n    id = Column(Integer, primary_key=True)\n    name = Column(String(50))\n\nengine = create_engine("sqlite:///:memory:")\nBase.metadata.create_all(engine)\n\nsession = Session(engine)\nsession.add(User(name="Alice"))\nsession.commit()\n\nusers = session.query(User).filter(User.name == "Alice").all()\nprint(users[0].name)\nsession.close()',
            'expected': 'Alice',
            'explain': 'session.query()创建查询，.filter()添加条件，.all()/.first()获取结果。等价于SELECT-WHERE SQL。',
            'difficulty': 'intermediate',
        },
        {
            'id': 'db_batch_insert',
            'title': '批量插入数据',
            'desc': '用 executemany 批量插入多条记录',
            'diff': 'intermediate',
            'kp': ['db_sqlite'],
            'template': 'import sqlite3\n\nconn = sqlite3.connect(":memory:")\ncursor = conn.cursor()\ncursor.execute("CREATE TABLE scores (name TEXT, score INTEGER)")\n\ndata = [("Alice", 90), ("Bob", 85), ("Carol", 95)]\ncursor.____________("INSERT INTO scores VALUES (?, ?)", data)\nconn.commit()\n\ncursor.execute("SELECT AVG(score) FROM scores")\nprint(cursor.fetchone()[0])',
            'test_input': '',
            'answer': 'import sqlite3\n\nconn = sqlite3.connect(":memory:")\ncursor = conn.cursor()\ncursor.execute("CREATE TABLE scores (name TEXT, score INTEGER)")\n\ndata = [("Alice", 90), ("Bob", 85), ("Carol", 95)]\ncursor.executemany("INSERT INTO scores VALUES (?, ?)", data)\nconn.commit()\n\ncursor.execute("SELECT AVG(score) FROM scores")\nprint(cursor.fetchone()[0])',
            'expected': '90.0',
            'explain': '批量插入：session.add_all([对象列表])一次性添加多条记录，比循环单条插入效率高。',
            'difficulty': 'intermediate',
        },
        {
            'id': 'db_transaction',
            'title': '事务处理',
            'desc': '用 with 语句管理事务，回滚异常操作',
            'diff': 'challenge',
            'kp': ['db_transaction'],
            'template': 'import sqlite3\n\nconn = sqlite3.connect(":memory:")\ncursor = conn.cursor()\ncursor.execute("CREATE TABLE accounts (name TEXT, balance INTEGER)")\ncursor.execute("INSERT INTO accounts VALUES (\'Alice\', 1000)")\ncursor.execute("INSERT INTO accounts VALUES (\'Bob\', 500)")\nconn.commit()\n\ndef transfer(conn, from_name, to_name, amount):\n    try:\n        cursor = conn.cursor()\n        cursor.execute("UPDATE accounts SET balance = balance - ? WHERE name = ?",\n                       (amount, from_name))\n        cursor.execute("UPDATE accounts SET balance = balance + ? WHERE name = ?",\n                       (amount, to_name))\n        if amount < 0:\n            raise ValueError("Amount must be positive")\n        conn.____________()\n    except Exception:\n        conn.____________()\n        raise\n\n# 正常转账\ntransfer(conn, "Alice", "Bob", 200)\ncursor.execute("SELECT balance FROM accounts WHERE name=\'Alice\'")\nprint(cursor.fetchone()[0])',
            'test_input': '',
            'answer': 'import sqlite3\n\nconn = sqlite3.connect(":memory:")\ncursor = conn.cursor()\ncursor.execute("CREATE TABLE accounts (name TEXT, balance INTEGER)")\ncursor.execute("INSERT INTO accounts VALUES (\'Alice\', 1000)")\ncursor.execute("INSERT INTO accounts VALUES (\'Bob\', 500)")\nconn.commit()\n\ndef transfer(conn, from_name, to_name, amount):\n    try:\n        cursor = conn.cursor()\n        cursor.execute("UPDATE accounts SET balance = balance - ? WHERE name = ?",\n                       (amount, from_name))\n        cursor.execute("UPDATE accounts SET balance = balance + ? WHERE name = ?",\n                       (amount, to_name))\n        if amount < 0:\n            raise ValueError("Amount must be positive")\n        conn.commit()\n    except Exception:\n        conn.rollback()\n        raise\n\ntransfer(conn, "Alice", "Bob", 200)\ncursor.execute("SELECT balance FROM accounts WHERE name=\'Alice\'")\nprint(cursor.fetchone()[0])',
            'expected': '800',
            'explain': '事务保证原子性：session.commit()提交，session.rollback()回滚。出错时撤销所有未提交的变更。',
            'difficulty': 'challenge',
        },
    ],
    20: [
        {
            'id': 'test_unittest_basic',
            'title': 'unittest 基本断言',
            'desc': '用 unittest 测试字符串操作函数',
            'diff': 'basic',
            'kp': ['test_unittest'],
            'template': 'import unittest\n\ndef capitalize_words(text):\n    return text.title()\n\nclass TestCapitalize(unittest.TestCase):\n    def test_basic(self):\n        self.____________(capitalize_words("hello world"), "Hello World")\n\n    def test_empty(self):\n        self.assertEqual(capitalize_words(""), "")\n\nprint("Tests defined")',
            'test_input': '',
            'answer': 'import unittest\n\ndef capitalize_words(text):\n    return text.title()\n\nclass TestCapitalize(unittest.TestCase):\n    def test_basic(self):\n        self.assertEqual(capitalize_words("hello world"), "Hello World")\n\n    def test_empty(self):\n        self.assertEqual(capitalize_words(""), "")\n\nprint("Tests defined")',
            'expected': 'Tests defined',
            'explain': 'unittest.TestCase提供断言方法：assertEqual/assertTrue/assertRaises。test_前缀的方法自动被发现。',
            'difficulty': 'basic',
        },
        {
            'id': 'test_pytest_fixture',
            'title': 'pytest fixture',
            'desc': '用 fixture 提供测试数据',
            'diff': 'basic',
            'kp': ['test_pytest', 'test_fixture'],
            'template': 'import pytest\n\n@pytest.____________\ndef sample_list():\n    return [1, 2, 3, 4, 5]\n\ndef test_sum(sample_list):\n    ____________ sum(sample_list) == 15\n\ndef test_len(sample_list):\n    assert len(sample_list) == 5\n\nprint("Fixtures defined")',
            'test_input': '',
            'answer': 'import pytest\n\n@pytest.fixture\ndef sample_list():\n    return [1, 2, 3, 4, 5]\n\ndef test_sum(sample_list):\n    assert sum(sample_list) == 15\n\ndef test_len(sample_list):\n    assert len(sample_list) == 5\n\nprint("Fixtures defined")',
            'expected': 'Fixtures defined',
            'explain': "pytest fixture用@pytest.fixture定义，通过参数注入测试函数。scope='module'每模块只执行一次。",
            'difficulty': 'basic',
        },
        {
            'id': 'test_pytest_parametrize',
            'title': '参数化测试',
            'desc': '用 parametrize 测试多组输入输出',
            'diff': 'intermediate',
            'kp': ['test_pytest', 'test_parametrize'],
            'template': 'import pytest\n\ndef is_palindrome(s):\n    return s == s[::-1]\n\n@pytest.mark.____________("input,expected", [\n    ("radar", True),\n    ("hello", False),\n    ("", True),\n    ("a", True),\n])\ndef test_palindrome(input, expected):\n    ____________ is_palindrome(input) == expected\n\nprint("Parametrize tests defined")',
            'test_input': '',
            'answer': 'import pytest\n\ndef is_palindrome(s):\n    return s == s[::-1]\n\n@pytest.mark.parametrize("input,expected", [\n    ("radar", True),\n    ("hello", False),\n    ("", True),\n    ("a", True),\n])\ndef test_palindrome(input, expected):\n    assert is_palindrome(input) == expected\n\nprint("Parametrize tests defined")',
            'expected': 'Parametrize tests defined',
            'explain': '@pytest.mark.parametrize装饰器实现参数化测试，多组输入自动生成多个测试用例。',
            'difficulty': 'intermediate',
        },
        {
            'id': 'test_logging_config',
            'title': '日志配置',
            'desc': '配置带格式和文件输出的日志',
            'diff': 'intermediate',
            'kp': ['test_logging'],
            'template': 'import logging\n\nlogging.basicConfig(\n    level=logging.____________,\n    format="%(asctime)s [%(levelname)s] %(message)s",\n    handlers=[\n        logging.FileHandler("test.log", encoding="utf-8"),\n    ]\n)\nlogger = logging.getLogger(__name__)\nlogger.____________("Application started")\nprint("Logger configured")',
            'test_input': '',
            'answer': 'import logging\n\nlogging.basicConfig(\n    level=logging.INFO,\n    format="%(asctime)s [%(levelname)s] %(message)s",\n    handlers=[\n        logging.FileHandler("test.log", encoding="utf-8"),\n    ]\n)\nlogger = logging.getLogger(__name__)\nlogger.info("Application started")\nprint("Logger configured")',
            'expected': 'Logger configured',
            'explain': 'logging模块分层日志：DEBUG/INFO/WARNING/ERROR/CRITICAL。basicConfig配置格式和输出目标。',
            'difficulty': 'intermediate',
        },
        {
            'id': 'test_exception_testing',
            'title': '异常测试',
            'desc': '测试函数在异常情况下是否抛出正确的异常',
            'diff': 'challenge',
            'kp': ['test_unittest', 'test_exception'],
            'template': 'import unittest\n\ndef safe_divide(a, b):\n    if b == 0:\n        raise ValueError("Division by zero")\n    return a / b\n\nclass TestSafeDivide(unittest.TestCase):\n    def test_normal(self):\n        self.assertEqual(safe_divide(10, 2), 5.0)\n\n    def test_zero_division(self):\n        with self.____________(ValueError) as ctx:\n            safe_divide(10, 0)\n        self.____________("zero", str(ctx.exception).lower())\n\nprint("Exception tests defined")',
            'test_input': '',
            'answer': 'import unittest\n\ndef safe_divide(a, b):\n    if b == 0:\n        raise ValueError("Division by zero")\n    return a / b\n\nclass TestSafeDivide(unittest.TestCase):\n    def test_normal(self):\n        self.assertEqual(safe_divide(10, 2), 5.0)\n\n    def test_zero_division(self):\n        with self.assertRaises(ValueError) as ctx:\n            safe_divide(10, 0)\n        self.assertIn("zero", str(ctx.exception).lower())\n\nprint("Exception tests defined")',
            'expected': 'Exception tests defined',
            'explain': '测试异常：pytest.raises(ExpectedException)上下文管理器，断言代码抛出指定异常。',
            'difficulty': 'challenge',
        },
    ],
    21: [
        {
            'id': 'api_basic_route',
            'title': 'FastAPI 基本路由',
            'desc': '创建一个 GET 接口返回问候语',
            'diff': 'basic',
            'kp': ['api_fastapi', 'api_route'],
            'template': 'from fastapi import FastAPI\n\napp = FastAPI()\n\n@app.____________("/hello")\ndef hello():\n    return {"message": "Hello, FastAPI!"}\n\n# 测试：访问 /hello 应返回 {"message": "Hello, FastAPI!"}\nprint("Route created")',
            'test_input': '',
            'answer': 'from fastapi import FastAPI\n\napp = FastAPI()\n\n@app.get("/hello")\ndef hello():\n    return {"message": "Hello, FastAPI!"}\n\nprint("Route created")',
            'expected': 'Route created',
            'explain': "FastAPI用装饰器定义路由：@app.get('/路径')。函数返回值自动序列化为JSON。",
            'difficulty': 'basic',
        },
        {
            'id': 'api_path_param',
            'title': '路径参数与类型',
            'desc': '创建带路径参数的接口，参数为 int 类型',
            'diff': 'basic',
            'kp': ['api_fastapi', 'api_params'],
            'template': 'from fastapi import FastAPI\n\napp = FastAPI()\n\n@app.get("/users/{{user_id}}")\ndef get_user(____________: int):\n    return {"id": user_id, "name": f"User {{user_id}}"}\n\nprint("Path param route created")',
            'test_input': '',
            'answer': 'from fastapi import FastAPI\n\napp = FastAPI()\n\n@app.get("/users/{user_id}")\ndef get_user(user_id: int):\n    return {"id": user_id, "name": f"User {{user_id}}"}\n\nprint("Path param route created")',
            'expected': 'Path param route created',
            'explain': '路径参数用{param}定义，函数参数指定类型。FastAPI自动校验类型，无效输入返回422。',
            'difficulty': 'basic',
        },
        {
            'id': 'api_pydantic',
            'title': 'Pydantic 请求体验证',
            'desc': '定义一个请求体模型，包含 name 和 price 字段',
            'diff': 'intermediate',
            'kp': ['api_pydantic', 'api_fastapi'],
            'template': 'from pydantic import BaseModel\nfrom typing import Optional\n\nclass ProductCreate(BaseModel):\n    name: str\n    price: ____________\n    description: ____________[str] = None\n\n# 验证\np = ProductCreate(name="Widget", price=9.99)\nprint(p.name, p.price)',
            'test_input': '',
            'answer': 'from pydantic import BaseModel\nfrom typing import Optional\n\nclass ProductCreate(BaseModel):\n    name: str\n    price: float\n    description: Optional[str] = None\n\np = ProductCreate(name="Widget", price=9.99)\nprint(p.name, p.price)',
            'expected': 'Widget 9.99',
            'explain': 'Pydantic BaseModel定义请求体结构，类型注解自动校验。FastAPI依赖注入接收validated数据。',
            'difficulty': 'intermediate',
        },
        {
            'id': 'api_crud_delete',
            'title': 'DELETE 接口',
            'desc': '实现删除接口，找不到时返回404',
            'diff': 'intermediate',
            'kp': ['api_crud', 'api_fastapi'],
            'template': 'from fastapi import FastAPI, HTTPException\n\napp = FastAPI()\nitems = {{1: "Apple", 2: "Banana"}}\n\n@app.delete("/items/{{item_id}}")\ndef delete_item(item_id: int):\n    if item_id not in items:\n        raise ____________(status_code=404, detail="Not found")\n    del items[item_id]\n    return {"deleted": ____________}\n\nprint("Delete route created")',
            'test_input': '',
            'answer': 'from fastapi import FastAPI, HTTPException\n\napp = FastAPI()\nitems = {{1: "Apple", 2: "Banana"}}\n\n@app.delete("/items/{item_id}")\ndef delete_item(item_id: int):\n    if item_id not in items:\n        raise HTTPException(status_code=404, detail="Not found")\n    del items[item_id]\n    return {"deleted": True}\n\nprint("Delete route created")',
            'expected': 'Delete route created',
            'explain': 'DELETE接口用于删除资源，通常通过路径参数指定ID。返回确认信息或204 No Content。',
            'difficulty': 'intermediate',
        },
        {
            'id': 'api_jwt_create',
            'title': 'JWT Token 生成',
            'desc': '用 python-jose 生成 JWT token',
            'diff': 'challenge',
            'kp': ['api_jwt'],
            'template': 'from jose import jwt\n\nSECRET = "mysecret"\nALGO = "HS256"\n\ndef create_token(data: dict):\n    token = jwt.____________(data, SECRET, algorithm=ALGO)\n    return token\n\ndef decode_token(token: str):\n    payload = jwt.____________(token, SECRET, algorithms=[ALGO])\n    return payload\n\ntoken = create_token({{"sub": "alice", "role": "admin"}})\npayload = decode_token(token)\nprint(payload["sub"])',
            'test_input': '',
            'answer': 'from jose import jwt\n\nSECRET = "mysecret"\nALGO = "HS256"\n\ndef create_token(data: dict):\n    token = jwt.encode(data, SECRET, algorithm=ALGO)\n    return token\n\ndef decode_token(token: str):\n    payload = jwt.decode(token, SECRET, algorithms=[ALGO])\n    return payload\n\ntoken = create_token({{"sub": "alice", "role": "admin"}})\npayload = decode_token(token)\nprint(payload["sub"])',
            'expected': 'alice',
            'explain': 'JWT Token=Header.Payload.Signature。PyJWT的jwt.encode()生成令牌，设置过期时间增强安全性。',
            'difficulty': 'challenge',
        },
    ],
}
