"""卡码网精选算法练习 — ACM模式实战

从 kamacoder.com 精选 30 道典型算法题，按难度分三级：
  - 入门篇 (10题): 基础输入输出、模拟、简单排序
  - 进阶篇 (10题): DP、贪心、二分、DFS/BFS
  - 挑战篇 (10题): 图论、高级DP、回溯、综合

每题提供：
  - id:        卡码网题号
  - title:     中文标题
  - url:       题目链接
  - desc:      简要描述（输入输出格式）
  - category:  算法分类
  - diff:      难度 basic / intermediate / challenge
  - kp:        关联知识点（与 ui.py KNOWLEDGE 对齐）
  - hint:      解题提示
  - template:  代码模板（含 ACM 输入框架）
  - answer:    参考答案
  - test_input:测试输入
  - expected:  期望输出

用法：
  from .kamacoder_practice import KAMACODER_PRACTICE
"""
from typing import Dict, List

KAMACODER_PRACTICE = {
    'basic': [
        {
            'id': 1,
            'title': 'A+B问题I',
            'desc': '输入两个整数a和b，输出a+b的值。多组测试数据，每行一组。',
            'diff': 'basic',
            'kp': ['var_create', 'op_arithmetic', 'print_basic'],
            'hint': 'while True + try/except 处理多组输入',
            'template': '# A+B问题I\n# 输入：每行两个整数，输出：a+b\nimport sys\nfor line in sys.stdin:\n    pass  # 在此写代码\n',
            'test_input': '1 2\n3 5\n10 20\n',
            'answer': 'import sys\nfor line in sys.stdin:\n    a, b = map(int, line.split())\n    print(a + b)\n',
            'expected': '3\n8\n30\n',
            'explain': 'A+B问题是最基础的输入输出练习。注意读取多行输入直到EOF，用sys.stdin或try-except处理。',
            'url': 'https://kamacoder.com/problempage.php?pid=1001',
            'category': '模拟',
        },
        {
            'id': 7,
            'title': '平均绩点',
            'desc': '每行输入若干字母等级(A/B/C/D/F)，计算平均绩点(A=4,B=3,C=2,D=1,F=0)，输出保留2位小数。输入一行0结束。',
            'diff': 'basic',
            'kp': ['if_elif', 'list_methods', 'print_format'],
            'hint': '用字典映射等级到分数，sum/len 算平均',
            'template': "# 平均绩点\ngrade_map = {'A': 4, 'B': 3, 'C': 2, 'D': 1, 'F': 0}\nwhile True:\n    line = input().strip()\n    if line == '0':\n        break\n    pass  # 在此写代码\n",
            'test_input': 'A B C D\nA A A\n0\n',
            'answer': "grade_map = {'A': 4, 'B': 3, 'C': 2, 'D': 1, 'F': 0}\nwhile True:\n    line = input().strip()\n    if line == '0':\n        break\n    grades = line.split()\n    total = sum(grade_map[g] for g in grades)\n    avg = total / len(grades)\n    print(f'{avg:.2f}')\n",
            'expected': '2.50\n4.00\n',
            'explain': '字符串反转：切片[::-1]最简洁，也可用reversed()。注意输出格式要求。',
            'url': 'https://kamacoder.com/problempage.php?pid=1007',
            'category': '模拟',
        },
        {
            'id': 12,
            'title': '打印数字图形',
            'desc': '输入n(1-9)，打印数字菱形。如n=3:\n  1\n 121\n12321\n 121\n  1',
            'diff': 'basic',
            'kp': ['for_loop', 'nested_loop', 'print_format'],
            'hint': '上半1~n行，下半n-1~1行，用空格+数字字符串构造',
            'template': '# 打印数字图形\nn = int(input())\n# 上半部分\nfor i in range(1, n + 1):\n    pass  # 在此写代码\n# 下半部分\nfor i in range(n - 1, 0, -1):\n    pass  # 在此写代码\n',
            'test_input': '3\n',
            'answer': "n = int(input())\nfor i in range(1, n + 1):\n    print(' ' * (n - i), end='')\n    for j in range(1, i + 1):\n        print(j, end='')\n    for j in range(i - 1, 0, -1):\n        print(j, end='')\n    print()\nfor i in range(n - 1, 0, -1):\n    print(' ' * (n - i), end='')\n    for j in range(1, i + 1):\n        print(j, end='')\n    for j in range(i - 1, 0, -1):\n        print(j, end='')\n    print()\n",
            'expected': '  1\n 121\n12321\n 121\n  1\n',
            'explain': '排序后取最值：sorted(lst)[-1]或max(lst)。注意数据范围和输入格式。',
            'url': 'https://kamacoder.com/problempage.php?pid=1012',
            'category': '模拟',
        },
        {
            'id': 43,
            'title': '汽水瓶换饮料',
            'desc': 'n个空瓶换汽水，3个空瓶换1瓶。输入若干n(1-100)，输出最多能喝几瓶。n=0结束。',
            'diff': 'basic',
            'kp': ['while_loop', 'op_arithmetic'],
            'hint': '模拟：每次用3瓶换1瓶，喝完又得1空瓶，直到不足3瓶。最后剩2瓶可借1瓶换1瓶再还。',
            'template': '# 汽水瓶换饮料\nwhile True:\n    n = int(input())\n    if n == 0:\n        break\n    pass  # 在此写代码\n',
            'test_input': '10\n3\n0\n',
            'answer': 'while True:\n    n = int(input())\n    if n == 0:\n        break\n    total = 0\n    empty = n\n    while empty >= 3:\n        new = empty // 3\n        total += new\n        empty = empty % 3 + new\n    if empty == 2:\n        total += 1\n    print(total)\n',
            'expected': '5\n1\n',
            'explain': 'n层菱形：上半部1到n行递增，下半部n-1到1递减。每行居中打印星号。',
            'url': 'https://kamacoder.com/problempage.php?pid=1043',
            'category': '模拟',
        },
        {
            'id': 50,
            'title': '随机数排序',
            'desc': '输入n(1-100)及n个1-500的随机整数，去重后升序输出。',
            'diff': 'basic',
            'kp': ['set_operations', 'list_methods', 'for_loop'],
            'hint': '用 set 去重，sorted 排序',
            'template': '# 随机数排序\nimport sys\nlines = sys.stdin.read().strip().split()\nn = int(lines[0])\nnums = [int(x) for x in lines[1:n+1]]\n# 在此写代码\n',
            'test_input': '8\n1 2 3 2 1 5 4 3\n',
            'answer': "import sys\nlines = sys.stdin.read().strip().split()\nn = int(lines[0])\nnums = [int(x) for x in lines[1:n+1]]\nunique = sorted(set(nums))\nprint(' '.join(map(str, unique)))\n",
            'expected': '1 2 3 4 5\n',
            'explain': '闰年判断：(year%4==0 and year%100!=0) or year%400==0。注意多组输入。',
            'url': 'https://kamacoder.com/problempage.php?pid=1050',
            'category': '排序',
        },
        {
            'id': 54,
            'title': '替换数字',
            'desc': "输入一个字符串，把所有数字字符替换为number。如'a1b2c' → 'anumberbnumberc'",
            'diff': 'basic',
            'kp': ['str_methods', 'for_loop', 'str_concat'],
            'hint': '遍历字符，isdigit() 判断，拼接替换',
            'template': "# 替换数字\ns = input()\nresult = []\nfor ch in s:\n    pass  # 在此写代码\nprint(''.join(result))\n",
            'test_input': 'a1b2c3\n',
            'answer': "s = input()\nresult = []\nfor ch in s:\n    if ch.isdigit():\n        result.append('number')\n    else:\n        result.append(ch)\nprint(''.join(result))\n",
            'expected': 'anumberbnumbercnumber\n',
            'explain': '斐波那契：f(1)=1, f(2)=1, f(n)=f(n-1)+f(n-2)。用迭代避免递归超时。',
            'url': 'https://kamacoder.com/problempage.php?pid=1064',
            'category': '字符串',
        },
        {
            'id': 55,
            'title': '右旋字符串',
            'desc': "输入k和字符串s，将s右旋k位。如k=2, s='abcdefg' → 'fgabcde'",
            'diff': 'basic',
            'kp': ['str_slice', 'op_arithmetic'],
            'hint': 's[-k:] + s[:-k]',
            'template': '# 右旋字符串\nk = int(input())\ns = input()\n# 在此写代码\n',
            'test_input': '2\nabcdefg\n',
            'answer': 'k = int(input())\ns = input()\nn = len(s)\nk = k % n\nprint(s[-k:] + s[:-k])\n',
            'expected': 'fgabcde\n',
            'explain': '水仙花数：各位数字的立方和等于原数。遍历100-999逐个检查。',
            'url': 'https://kamacoder.com/problempage.php?pid=1065',
            'category': '字符串',
        },
        {
            'id': 58,
            'title': '区间和',
            'desc': '输入n个数，再输入若干区间[a,b]，输出区间和。用前缀和优化。',
            'diff': 'basic',
            'kp': ['list_index', 'for_loop', 'op_arithmetic'],
            'hint': '前缀和 prefix[i] = sum(arr[:i])，区间和 = prefix[b+1] - prefix[a]',
            'template': "# 区间和\nimport sys\nlines = sys.stdin.read().strip().split('\\n')\nn = int(lines[0])\narr = [int(lines[i+1]) for i in range(n)]\n# 构建前缀和\n# 在此写代码\n",
            'test_input': '5\n1\n2\n3\n4\n5\n0 1\n1 3\n',
            'answer': "import sys\nlines = sys.stdin.read().strip().split('\\n')\nn = int(lines[0])\narr = [int(lines[i+1]) for i in range(n)]\nprefix = [0] * (n + 1)\nfor i in range(n):\n    prefix[i+1] = prefix[i] + arr[i]\nfor line in lines[n+1:]:\n    if not line.strip():\n        continue\n    a, b = map(int, line.split())\n    print(prefix[b+1] - prefix[a])\n",
            'expected': '3\n9\n',
            'explain': '杨辉三角：每行首尾为1，中间元素=上一行左上+上一行右上。可用二维数组存储。',
            'url': 'https://kamacoder.com/problempage.php?pid=1070',
            'category': '前缀和',
        },
        {
            'id': 39,
            'title': '求和',
            'desc': '输入n个正整数，求两两之和的绝对值总和。即对每个a[i]，计算sum(|a[i]-a[j]|)对所有j。',
            'diff': 'basic',
            'kp': ['nested_loop', 'op_arithmetic', 'abs_func'],
            'hint': '排序后，用前缀和优化：对排序后的a[i]，左侧贡献 a[i]*i - prefix[i]',
            'template': "# 求和\nimport sys\nlines = sys.stdin.read().strip().split('\\n')\nn = int(lines[0])\narr = list(map(int, lines[1].split()))\n# 在此写代码\n",
            'test_input': '4\n1 3 6 9\n',
            'answer': "import sys\nlines = sys.stdin.read().strip().split('\\n')\nn = int(lines[0])\narr = list(map(int, lines[1].split()))\narr.sort()\nprefix = [0] * (n + 1)\nfor i in range(n):\n    prefix[i+1] = prefix[i] + arr[i]\ntotal = 0\nfor i in range(n):\n    total += arr[i] * i - prefix[i]\nprint(total)\n",
            'expected': '16\n',
            'explain': '素数判断：从2到sqrt(n)检查是否有因子。埃氏筛法适合批量筛选。',
            'url': 'https://kamacoder.com/problempage.php?pid=1039',
            'category': '模拟',
        },
        {
            'id': 61,
            'title': '出现一次的整数',
            'desc': '输入n和n个整数，找出只出现一次的数，按升序输出。',
            'diff': 'basic',
            'kp': ['dict_access', 'list_methods', 'for_loop'],
            'hint': '用字典统计频次，筛选值为1的键',
            'template': "# 出现一次的整数\nimport sys\nlines = sys.stdin.read().strip().split('\\n')\nn = int(lines[0])\narr = list(map(int, lines[1].split()))\n# 在此写代码\n",
            'test_input': '7\n1 2 3 2 4 1 5\n',
            'answer': "import sys\nlines = sys.stdin.read().strip().split('\\n')\nn = int(lines[0])\narr = list(map(int, lines[1].split()))\ncount = {}\nfor x in arr:\n    count[x] = count.get(x, 0) + 1\nresult = sorted(k for k, v in count.items() if v == 1)\nprint(' '.join(map(str, result)))\n",
            'expected': '3 4 5\n',
            'explain': '质因数分解：从小到大试除，每除尽一个因子就记录。注意1的特殊处理。',
            'url': 'https://kamacoder.com/problempage.php?pid=1081',
            'category': '哈希',
        },
    ],
    'intermediate': [
        {
            'id': 24,
            'title': '最长公共子序列',
            'desc': '输入两个字符串，输出最长公共子序列(LCS)的长度。',
            'diff': 'intermediate',
            'kp': ['algo_dp', 'nested_loop', 'list_index'],
            'hint': 'dp[i][j] = dp[i-1][j-1]+1 (if s1[i-1]==s2[j-1]) else max(dp[i-1][j], dp[i][j-1])',
            'template': '# 最长公共子序列\nimport sys\nfor line in sys.stdin:\n    s1, s2 = line.strip().split()\n    m, n = len(s1), len(s2)\n    dp = [[0]*(n+1) for _ in range(m+1)]\n    # 在此写代码\n',
            'test_input': 'abcde ace\n',
            'answer': 'import sys\nfor line in sys.stdin:\n    s1, s2 = line.strip().split()\n    m, n = len(s1), len(s2)\n    dp = [[0]*(n+1) for _ in range(m+1)]\n    for i in range(1, m+1):\n        for j in range(1, n+1):\n            if s1[i-1] == s2[j-1]:\n                dp[i][j] = dp[i-1][j-1] + 1\n            else:\n                dp[i][j] = max(dp[i-1][j], dp[i][j-1])\n    print(dp[m][n])\n',
            'expected': '3\n',
            'explain': '爬楼梯DP：dp[i]=dp[i-1]+dp[i-2]，到第i阶的方法数等于从i-1和i-2阶上来之和。',
            'url': 'https://kamacoder.com/problempage.php?pid=1023',
            'category': '动态规划',
        },
        {
            'id': 27,
            'title': '最长递增子序列',
            'desc': '输入n和n个整数，输出最长严格递增子序列的长度。',
            'diff': 'intermediate',
            'kp': ['algo_dp', 'nested_loop', 'list_index'],
            'hint': 'dp[i] = max(dp[j]+1) for all j<i where arr[j]<arr[i]',
            'template': "# 最长递增子序列\nimport sys\nlines = sys.stdin.read().strip().split('\\n')\nn = int(lines[0])\narr = list(map(int, lines[1].split()))\ndp = [1] * n\n# 在此写代码\n",
            'test_input': '8\n10 9 2 5 3 7 101 18\n',
            'answer': "import sys\nlines = sys.stdin.read().strip().split('\\n')\nn = int(lines[0])\narr = list(map(int, lines[1].split()))\ndp = [1] * n\nfor i in range(1, n):\n    for j in range(i):\n        if arr[j] < arr[i]:\n            dp[i] = max(dp[i], dp[j] + 1)\nprint(max(dp))\n",
            'expected': '4\n',
            'explain': '最长公共子序列LCS：dp[i][j]表示s1[:i]和s2[:j]的LCS长度。相等则+1，不等取max。',
            'url': 'https://kamacoder.com/problempage.php?pid=1027',
            'category': '动态规划',
        },
        {
            'id': 57,
            'title': '爬楼梯（进阶）',
            'desc': 'n阶楼梯，每次可以爬1到m阶，求有多少种方法爬到顶。',
            'diff': 'intermediate',
            'kp': ['algo_dp', 'for_loop', 'nested_loop'],
            'hint': 'dp[i] = sum(dp[i-j]) for j in 1..m and i-j>=0',
            'template': '# 爬楼梯进阶\nimport sys\nfor line in sys.stdin:\n    n, m = map(int, line.split())\n    dp = [0] * (n + 1)\n    dp[0] = 1\n    # 在此写代码\n',
            'test_input': '3 2\n',
            'answer': 'import sys\nfor line in sys.stdin:\n    n, m = map(int, line.split())\n    dp = [0] * (n + 1)\n    dp[0] = 1\n    for i in range(1, n + 1):\n        for j in range(1, m + 1):\n            if i - j >= 0:\n                dp[i] += dp[i - j]\n    print(dp[n])\n',
            'expected': '3\n',
            'explain': '岛屿数量DFS/BFS：遍历网格，遇到1就开始DFS/BFS标记整个岛屿为已访问，计数+1。',
            'url': 'https://kamacoder.com/problempage.php?pid=1067',
            'category': '动态规划',
        },
        {
            'id': 46,
            'title': '携带研究材料',
            'desc': '01背包问题：M种研究材料，每种只有1份，背包容量N，求最大价值。',
            'diff': 'intermediate',
            'kp': ['algo_dp', 'nested_loop', 'list_index'],
            'hint': '一维dp倒序：dp[j] = max(dp[j], dp[j-w[i]]+v[i])',
            'template': "# 携带研究材料(01背包)\nimport sys\nlines = sys.stdin.read().strip().split('\\n')\nM, N = map(int, lines[0].split())\nweights, values = [], []\nfor i in range(1, M + 1):\n    w, v = map(int, lines[i].split())\n    weights.append(w)\n    values.append(v)\ndp = [0] * (N + 1)\n# 在此写代码\n",
            'test_input': '3 4\n1 2\n2 3\n3 4\n',
            'answer': "import sys\nlines = sys.stdin.read().strip().split('\\n')\nM, N = map(int, lines[0].split())\nweights, values = [], []\nfor i in range(1, M + 1):\n    w, v = map(int, lines[i].split())\n    weights.append(w)\n    values.append(v)\ndp = [0] * (N + 1)\nfor i in range(M):\n    for j in range(N, weights[i] - 1, -1):\n        dp[j] = max(dp[j], dp[j - weights[i]] + values[i])\nprint(dp[N])\n",
            'expected': '6\n',
            'explain': '区间和(前缀和)：prefix[i]=prefix[i-1]+arr[i-1]，区间[l,r]和=prefix[r+1]-prefix[l]。',
            'url': 'https://kamacoder.com/problempage.php?pid=1056',
            'category': '动态规划',
        },
        {
            'id': 52,
            'title': '携带研究材料II',
            'desc': '完全背包问题：M种研究材料，每种无限份，背包容量N，求最大价值。',
            'diff': 'intermediate',
            'kp': ['algo_dp', 'nested_loop', 'list_index'],
            'hint': '一维dp正序：dp[j] = max(dp[j], dp[j-w[i]]+v[i])，与01背包的区别是内层正序遍历',
            'template': "# 携带研究材料II(完全背包)\nimport sys\nlines = sys.stdin.read().strip().split('\\n')\nM, N = map(int, lines[0].split())\nweights, values = [], []\nfor i in range(1, M + 1):\n    w, v = map(int, lines[i].split())\n    weights.append(w)\n    values.append(v)\ndp = [0] * (N + 1)\n# 在此写代码\n",
            'test_input': '3 4\n1 2\n2 3\n3 4\n',
            'answer': "import sys\nlines = sys.stdin.read().strip().split('\\n')\nM, N = map(int, lines[0].split())\nweights, values = [], []\nfor i in range(1, M + 1):\n    w, v = map(int, lines[i].split())\n    weights.append(w)\n    values.append(v)\ndp = [0] * (N + 1)\nfor i in range(M):\n    for j in range(weights[i], N + 1):\n        dp[j] = max(dp[j], dp[j - weights[i]] + values[i])\nprint(dp[N])\n",
            'expected': '8\n',
            'explain': '所有可达路径(图DFS)：邻接表建图，从起点DFS到终点，记录所有路径。',
            'url': 'https://kamacoder.com/problempage.php?pid=1062',
            'category': '动态规划',
        },
        {
            'id': 41,
            'title': '岛屿数量',
            'desc': '给定n×m矩阵(1=陆地,0=水)，求岛屿数量。岛屿由上下左右相连的陆地组成。',
            'diff': 'intermediate',
            'kp': ['algo_graph_dfs', 'algo_graph_bfs', 'nested_loop'],
            'hint': '遍历网格，遇到1就DFS把相连的1全变0，计数+1',
            'template': "# 岛屿数量\nimport sys\nlines = sys.stdin.read().strip().split('\\n')\nn, m = map(int, lines[0].split())\ngrid = []\nfor i in range(1, n + 1):\n    grid.append(list(map(int, lines[i].split())))\n\ndef dfs(x, y):\n    pass  # 在此写代码\n\ncount = 0\n# 在此写代码\nprint(count)\n",
            'test_input': '4 5\n1 1 0 0 0\n1 1 0 0 0\n0 0 1 0 0\n0 0 0 1 1\n',
            'answer': "import sys\nlines = sys.stdin.read().strip().split('\\n')\nn, m = map(int, lines[0].split())\ngrid = []\nfor i in range(1, n + 1):\n    grid.append(list(map(int, lines[i].split())))\n\ndef dfs(x, y):\n    if x < 0 or x >= n or y < 0 or y >= m or grid[x][y] == 0:\n        return\n    grid[x][y] = 0\n    dfs(x+1, y)\n    dfs(x-1, y)\n    dfs(x, y+1)\n    dfs(x, y-1)\n\ncount = 0\nfor i in range(n):\n    for j in range(m):\n        if grid[i][j] == 1:\n            dfs(i, j)\n            count += 1\nprint(count)\n",
            'expected': '3\n',
            'explain': '岛屿最大面积：DFS时统计当前岛屿面积，维护全局最大值。',
            'url': 'https://kamacoder.com/problempage.php?pid=1041',
            'category': 'DFS/BFS',
        },
        {
            'id': 100,
            'title': '岛屿的最大面积',
            'desc': '给定n×m矩阵(1=陆地,0=水)，求最大岛屿面积。',
            'diff': 'intermediate',
            'kp': ['algo_graph_dfs', 'algo_recursive', 'nested_loop'],
            'hint': 'DFS返回面积，遍历所有格子取最大值',
            'template': "# 岛屿的最大面积\nimport sys\nlines = sys.stdin.read().strip().split('\\n')\nn, m = map(int, lines[0].split())\ngrid = []\nfor i in range(1, n + 1):\n    grid.append(list(map(int, lines[i].split())))\n\ndef dfs(x, y):\n    if x < 0 or x >= n or y < 0 or y >= m or grid[x][y] == 0:\n        return 0\n    grid[x][y] = 0\n    area = 1\n    # 在此写代码\n    return area\n\nmax_area = 0\nfor i in range(n):\n    for j in range(m):\n        if grid[i][j] == 1:\n            max_area = max(max_area, dfs(i, j))\nprint(max_area)\n",
            'test_input': '4 5\n1 1 0 0 0\n1 1 0 0 0\n0 0 1 0 0\n0 0 0 1 1\n',
            'answer': "import sys\nlines = sys.stdin.read().strip().split('\\n')\nn, m = map(int, lines[0].split())\ngrid = []\nfor i in range(1, n + 1):\n    grid.append(list(map(int, lines[i].split())))\n\ndef dfs(x, y):\n    if x < 0 or x >= n or y < 0 or y >= m or grid[x][y] == 0:\n        return 0\n    grid[x][y] = 0\n    area = 1\n    area += dfs(x+1, y)\n    area += dfs(x-1, y)\n    area += dfs(x, y+1)\n    area += dfs(x, y-1)\n    return area\n\nmax_area = 0\nfor i in range(n):\n    for j in range(m):\n        if grid[i][j] == 1:\n            max_area = max(max_area, dfs(i, j))\nprint(max_area)\n",
            'expected': '4\n',
            'explain': '01背包：dp[j]=max(dp[j], dp[j-w[i]]+v[i])，倒序遍历容量防重复选取。',
            'url': 'https://kamacoder.com/problempage.php?pid=1172',
            'category': 'DFS/BFS',
        },
        {
            'id': 98,
            'title': '所有可达路径',
            'desc': '给定有向图n个节点m条边，输出从节点1到节点n的所有路径。',
            'diff': 'intermediate',
            'kp': ['algo_graph_dfs', 'algo_recursive', 'list_methods'],
            'hint': 'DFS回溯，维护当前路径列表，到达n时记录',
            'template': "# 所有可达路径\nimport sys\nlines = sys.stdin.read().strip().split('\\n')\nn, m = map(int, lines[0].split())\ngraph = [[] for _ in range(n + 1)]\nfor i in range(1, m + 1):\n    s, t = map(int, lines[i].split())\n    graph[s].append(t)\n\nresult = []\ndef dfs(node, path):\n    pass  # 在此写代码\n\ndfs(1, [1])\nif not result:\n    print(-1)\nelse:\n    for p in result:\n        print(' '.join(map(str, p)))\n",
            'test_input': '5 5\n1 3\n3 5\n1 2\n2 4\n4 5\n',
            'answer': "import sys\nlines = sys.stdin.read().strip().split('\\n')\nn, m = map(int, lines[0].split())\ngraph = [[] for _ in range(n + 1)]\nfor i in range(1, m + 1):\n    s, t = map(int, lines[i].split())\n    graph[s].append(t)\n\nresult = []\ndef dfs(node, path):\n    if node == n:\n        result.append(path[:])\n        return\n    for neighbor in graph[node]:\n        path.append(neighbor)\n        dfs(neighbor, path)\n        path.pop()\n\ndfs(1, [1])\nif not result:\n    print(-1)\nelse:\n    for p in result:\n        print(' '.join(map(str, p)))\n",
            'expected': '1 3 5\n1 2 4 5\n',
            'explain': '完全背包：正序遍历容量（每个物品可选多次），dp[j]=max(dp[j], dp[j-w[i]]+v[i])。',
            'url': 'https://kamacoder.com/problempage.php?pid=1170',
            'category': 'DFS',
        },
        {
            'id': 108,
            'title': '冗余连接',
            'desc': 'n个节点n条边的无向图（多一条边），删除一条边使图变为树。返回最后出现在输入中的冗余边。',
            'diff': 'intermediate',
            'kp': ['algo_union_find', 'for_loop', 'list_index'],
            'hint': '并查集：遍历每条边，如果两端已在同一集合则为冗余边',
            'template': "# 冗余连接\nimport sys\nlines = sys.stdin.read().strip().split('\\n')\nn = int(lines[0])\nedges = []\nfor i in range(1, n + 1):\n    s, t = map(int, lines[i].split())\n    edges.append((s, t))\n\nparent = list(range(n + 1))\ndef find(x):\n    pass  # 在此写代码\n\ndef union(x, y):\n    pass  # 在此写代码\n\n# 在此写代码\n",
            'test_input': '3\n1 2\n1 3\n2 3\n',
            'answer': "import sys\nlines = sys.stdin.read().strip().split('\\n')\nn = int(lines[0])\nedges = []\nfor i in range(1, n + 1):\n    s, t = map(int, lines[i].split())\n    edges.append((s, t))\n\nparent = list(range(n + 1))\ndef find(x):\n    if parent[x] != x:\n        parent[x] = find(parent[x])\n    return parent[x]\n\ndef union(x, y):\n    px, py = find(x), find(y)\n    if px == py:\n        return False\n    parent[px] = py\n    return True\n\nfor s, t in edges:\n    if not union(s, t):\n        print(s, t)\n        break\n",
            'expected': '2 3\n',
            'explain': '组合总和IV：dp[i]=sum(dp[i-nums[j]])，注意题目求排列数不是组合数。',
            'url': 'https://kamacoder.com/problempage.php?pid=1180',
            'category': '并查集',
        },
        {
            'id': 125,
            'title': '连续子数组最大和',
            'desc': '输入n和n个整数，求连续子数组的最大和。',
            'diff': 'intermediate',
            'kp': ['algo_dp', 'for_loop', 'list_index'],
            'hint': 'dp[i] = max(dp[i-1]+arr[i], arr[i])，取全局最大值。即 Kadane 算法',
            'template': "# 连续子数组最大和\nimport sys\nlines = sys.stdin.read().strip().split('\\n')\nn = int(lines[0])\narr = list(map(int, lines[1].split()))\n# 在此写代码\n",
            'test_input': '6\n-2 1 -3 4 -1 2 1 -5 4\n',
            'answer': "import sys\nlines = sys.stdin.read().strip().split('\\n')\nn = int(lines[0])\narr = list(map(int, lines[1].split()))\ncur_max = arr[0]\nglobal_max = arr[0]\nfor i in range(1, n):\n    cur_max = max(arr[i], cur_max + arr[i])\n    global_max = max(global_max, cur_max)\nprint(global_max)\n",
            'expected': '6\n',
            'explain': '最短路径Dijkstra：优先队列维护最短边，每次松弛更新邻居距离。适合非负权图。',
            'url': 'https://kamacoder.com/problempage.php?pid=1195',
            'category': '动态规划',
        },
    ],
    'challenge': [
        {
            'id': 47,
            'title': '参加科学大会(Dijkstra)',
            'desc': 'n个节点m条有向边，求节点1到节点n的最短距离。',
            'diff': 'challenge',
            'kp': ['algo_graph_bfs', 'dict_access', 'algo_greedy'],
            'hint': 'Dijkstra：小顶堆，每次取最近未访问节点松弛',
            'template': "# Dijkstra最短路\nimport sys, heapq\nlines = sys.stdin.read().strip().split('\\n')\nn, m = map(int, lines[0].split())\ngraph = [[] for _ in range(n + 1)]\nfor i in range(1, m + 1):\n    s, t, v = map(int, lines[i].split())\n    graph[s].append((t, v))\n\n# 在此写代码\n",
            'test_input': '4 4\n1 2 1\n1 3 4\n2 3 2\n3 4 1\n',
            'answer': "import sys, heapq\nlines = sys.stdin.read().strip().split('\\n')\nn, m = map(int, lines[0].split())\ngraph = [[] for _ in range(n + 1)]\nfor i in range(1, m + 1):\n    s, t, v = map(int, lines[i].split())\n    graph[s].append((t, v))\n\ndist = [float('inf')] * (n + 1)\ndist[1] = 0\nheap = [(0, 1)]\nvisited = [False] * (n + 1)\n\nwhile heap:\n    d, u = heapq.heappop(heap)\n    if visited[u]:\n        continue\n    visited[u] = True\n    for v, w in graph[u]:\n        if dist[u] + w < dist[v]:\n            dist[v] = dist[u] + w\n            heapq.heappush(heap, (dist[v], v))\n\nprint(dist[n] if dist[n] != float('inf') else -1)\n",
            'expected': '4\n',
            'explain': 'N皇后：回溯法逐行放置，检查列和对角线冲突。剪枝条件：同列/同对角线跳过。',
            'url': 'https://kamacoder.com/problempage.php?pid=1047',
            'category': '图论-最短路',
        },
        {
            'id': 53,
            'title': '寻宝(Prim最小生成树)',
            'desc': 'n个村庄m条路，修路使所有村庄连通，求最小总费用。',
            'diff': 'challenge',
            'kp': ['algo_greedy', 'algo_graph_bfs', 'dict_access'],
            'hint': 'Prim：从节点1开始，每次选最近的未访问邻居加入',
            'template': "# Prim最小生成树\nimport sys, heapq\nlines = sys.stdin.read().strip().split('\\n')\nn, m = map(int, lines[0].split())\ngraph = [[] for _ in range(n + 1)]\nfor i in range(1, m + 1):\n    s, t, v = map(int, lines[i].split())\n    graph[s].append((t, v))\n    graph[t].append((s, v))\n\n# 在此写代码\n",
            'test_input': '4 5\n1 2 1\n1 3 2\n2 3 3\n2 4 4\n3 4 5\n',
            'answer': "import sys, heapq\nlines = sys.stdin.read().strip().split('\\n')\nn, m = map(int, lines[0].split())\ngraph = [[] for _ in range(n + 1)]\nfor i in range(1, m + 1):\n    s, t, v = map(int, lines[i].split())\n    graph[s].append((t, v))\n    graph[t].append((s, v))\n\nvisited = [False] * (n + 1)\nheap = [(0, 1)]\ntotal = 0\ncount = 0\n\nwhile heap and count < n:\n    cost, u = heapq.heappop(heap)\n    if visited[u]:\n        continue\n    visited[u] = True\n    total += cost\n    count += 1\n    for v, w in graph[u]:\n        if not visited[v]:\n            heapq.heappush(heap, (w, v))\n\nprint(total)\n",
            'expected': '7\n',
            'explain': '子集：回溯枚举每个元素选或不选，或者迭代逐步扩展子集。',
            'url': 'https://kamacoder.com/problempage.php?pid=1053',
            'category': '图论-MST',
        },
        {
            'id': 56,
            'title': '携带矿石资源(多重背包)',
            'desc': '多重背包：M种矿石，每种有限数量，背包容量N，求最大价值。',
            'diff': 'challenge',
            'kp': ['algo_dp', 'nested_loop', 'list_index'],
            'hint': '多重背包：将每种物品展开为01背包，或用二进制优化拆分',
            'template': "# 多重背包\nimport sys\nlines = sys.stdin.read().strip().split('\\n')\nC, N = map(int, lines[0].split())\nweights, values, counts = [], [], []\nfor i in range(1, C + 1):\n    w, v, c = map(int, lines[i].split())\n    weights.append(w)\n    values.append(v)\n    counts.append(c)\n\n# 在此写代码\n",
            'test_input': '3 10\n2 3 5\n3 4 3\n4 5 2\n',
            'answer': "import sys\nlines = sys.stdin.read().strip().split('\\n')\nC, N = map(int, lines[0].split())\nweights, values, counts = [], [], []\nfor i in range(1, C + 1):\n    w, v, c = map(int, lines[i].split())\n    weights.append(w)\n    values.append(v)\n    counts.append(c)\n\ndp = [0] * (N + 1)\nfor i in range(C):\n    for j in range(N, -1, -1):\n        for k in range(1, counts[i] + 1):\n            if j - k * weights[i] >= 0:\n                dp[j] = max(dp[j], dp[j - k * weights[i]] + k * values[i])\nprint(dp[N])\n",
            'expected': '15\n',
            'explain': '全排列：回溯+used标记已选元素，每次选一个未用元素加入当前排列。',
            'url': 'https://kamacoder.com/problempage.php?pid=1066',
            'category': '动态规划',
        },
        {
            'id': 122,
            'title': '滑动窗口最大值',
            'desc': '给定数组nums和窗口大小k，返回每个滑动窗口的最大值。',
            'diff': 'challenge',
            'kp': ['list_methods', 'for_loop', 'deque'],
            'hint': '用单调递减队列维护窗口最大值，队首即答案',
            'template': "# 滑动窗口最大值\nfrom collections import deque\nimport sys\nlines = sys.stdin.read().strip().split('\\n')\nn = int(lines[0])\nnums = list(map(int, lines[1].split()))\nk = int(lines[2])\n\n# 在此写代码\n",
            'test_input': '8\n1 3 -1 -3 5 3 6 7\n3\n',
            'answer': "from collections import deque\nimport sys\nlines = sys.stdin.read().strip().split('\\n')\nn = int(lines[0])\nnums = list(map(int, lines[1].split()))\nk = int(lines[2])\n\ndq = deque()\nresult = []\nfor i in range(n):\n    while dq and nums[dq[-1]] < nums[i]:\n        dq.pop()\n    dq.append(i)\n    if dq[0] <= i - k:\n        dq.popleft()\n    if i >= k - 1:\n        result.append(nums[dq[0]])\nprint(' '.join(map(str, result)))\n",
            'expected': '3 3 5 5 6 7\n',
            'explain': '括号生成：左括号数<n时可加左，右括号数<左括号数时可加右。DFS生成所有合法组合。',
            'url': 'https://kamacoder.com/problempage.php?pid=1192',
            'category': '单调队列',
        },
        {
            'id': 121,
            'title': '大数减法',
            'desc': '两个超长非负整数字符串，求它们的差（绝对值），不含前导零。',
            'diff': 'challenge',
            'kp': ['str_methods', 'for_loop', 'list_methods'],
            'hint': '比较大小确定正负，逐位相减借位',
            'template': "# 大数减法\nimport sys\nlines = sys.stdin.read().strip().split('\\n')\na = lines[0].strip()\nb = lines[1].strip()\n\ndef compare(s1, s2):\n    pass  # 在此写代码\n\ndef sub(s1, s2):\n    pass  # 在此写代码\n\n# 在此写代码\n",
            'test_input': '12345678901234567890\n9876543210\n',
            'answer': "import sys\nlines = sys.stdin.read().strip().split('\\n')\na = lines[0].strip()\nb = lines[1].strip()\n\ndef compare(s1, s2):\n    if len(s1) != len(s2):\n        return len(s1) - len(s2)\n    if s1 == s2:\n        return 0\n    return 1 if s1 > s2 else -1\n\ndef sub(s1, s2):\n    result = []\n    borrow = 0\n    i, j = len(s1) - 1, len(s2) - 1\n    while i >= 0:\n        d1 = int(s1[i])\n        d2 = int(s2[j]) if j >= 0 else 0\n        diff = d1 - d2 - borrow\n        if diff < 0:\n            diff += 10\n            borrow = 1\n        else:\n            borrow = 0\n        result.append(str(diff))\n        i -= 1\n        j -= 1\n    while len(result) > 1 and result[-1] == '0':\n        result.pop()\n    return ''.join(reversed(result))\n\ncmp = compare(a, b)\nif cmp >= 0:\n    print(sub(a, b))\nelse:\n    print('-' + sub(b, a))\n",
            'expected': '12345678901234567880\n',
            'explain': '编辑距离：dp[i][j]表示word1[:i]变word2[:j]的最少操作。增/删/换三选一取min。',
            'url': 'https://kamacoder.com/problempage.php?pid=1191',
            'category': '大数/模拟',
        },
        {
            'id': 93,
            'title': '括号序列',
            'desc': '给定括号序列，判断是否合法。合法：每个左括号有对应右括号且嵌套正确。',
            'diff': 'challenge',
            'kp': ['algo_stack_queue', 'list_methods', 'dict_access'],
            'hint': '用栈：左括号入栈，右括号检查栈顶是否匹配',
            'template': "# 括号序列\nimport sys\nfor line in sys.stdin:\n    s = line.strip()\n    stack = []\n    pairs = {')': '(', ']': '[', '}': '{'}\n    valid = True\n    # 在此写代码\n    print('yes' if valid and not stack else 'no')\n",
            'test_input': '([])\n([)]\n((\n',
            'answer': "import sys\nfor line in sys.stdin:\n    s = line.strip()\n    if not s:\n        print('yes')\n        continue\n    stack = []\n    pairs = {')': '(', ']': '[', '}': '{'}\n    valid = True\n    for ch in s:\n        if ch in '([{':\n            stack.append(ch)\n        elif ch in ')]}':\n            if not stack or stack[-1] != pairs[ch]:\n                valid = False\n                break\n            stack.pop()\n    print('yes' if valid and not stack else 'no')\n",
            'expected': 'yes\nno\nno\n',
            'explain': '最长递增子序列：dp[i]表示以nums[i]结尾的LIS长度。二分查找优化到O(n log n)。',
            'url': 'https://kamacoder.com/problempage.php?pid=1165',
            'category': '栈',
        },
        {
            'id': 104,
            'title': '建造最大岛屿',
            'desc': 'n×m矩阵，可以将一个0变1，求最大岛屿面积。',
            'diff': 'challenge',
            'kp': ['algo_graph_dfs', 'nested_loop', 'set_operations'],
            'hint': '先标记每个岛屿的编号和面积，再遍历每个0看相邻岛屿合并面积',
            'template': "# 建造最大岛屿\nimport sys\nlines = sys.stdin.read().strip().split('\\n')\nn, m = map(int, lines[0].split())\ngrid = []\nfor i in range(1, n + 1):\n    grid.append(list(map(int, lines[i].split())))\n\n# Step1: 标记岛屿编号和面积\n# Step2: 遍历0，看周围岛屿\n# 在此写代码\n",
            'test_input': '4 5\n1 1 0 0 0\n1 1 0 0 0\n0 0 1 0 0\n0 0 0 1 1\n',
            'answer': "import sys\nlines = sys.stdin.read().strip().split('\\n')\nn, m = map(int, lines[0].split())\ngrid = []\nfor i in range(1, n + 1):\n    grid.append(list(map(int, lines[i].split())))\n\nisland_id = 2\narea_map = {}\n\ndef dfs(x, y, iid):\n    if x < 0 or x >= n or y < 0 or y >= m or grid[x][y] != 1:\n        return 0\n    grid[x][y] = iid\n    a = 1\n    a += dfs(x+1, y, iid)\n    a += dfs(x-1, y, iid)\n    a += dfs(x, y+1, iid)\n    a += dfs(x, y-1, iid)\n    return a\n\nfor i in range(n):\n    for j in range(m):\n        if grid[i][j] == 1:\n            area = dfs(i, j, island_id)\n            area_map[island_id] = area\n            island_id += 1\n\nif not area_map:\n    print(1 if n > 0 and m > 0 else 0)\n    sys.exit(0)\n\nmax_area = max(area_map.values())\ndirs = [(0,1),(0,-1),(1,0),(-1,0)]\nfor i in range(n):\n    for j in range(m):\n        if grid[i][j] == 0:\n            seen = set()\n            total = 1\n            for dx, dy in dirs:\n                nx, ny = i + dx, j + dy\n                if 0 <= nx < n and 0 <= ny < m and grid[nx][ny] > 1:\n                    iid = grid[nx][ny]\n                    if iid not in seen:\n                        seen.add(iid)\n                        total += area_map[iid]\n            max_area = max(max_area, total)\nprint(max_area)\n",
            'expected': '6\n',
            'explain': '拓扑排序：BFS+入度表，每次移除入度为0的节点并减少邻居入度。检测环用DFS三色标记。',
            'url': 'https://kamacoder.com/problempage.php?pid=1176',
            'category': 'DFS/BFS',
        },
        {
            'id': 97,
            'title': '小明逛公园(Floyd)',
            'desc': 'n个节点m条带权边，若干查询，问从A到B的最短距离。',
            'diff': 'challenge',
            'kp': ['algo_graph_bfs', 'nested_loop', 'list_index'],
            'hint': 'Floyd-Warshall：三重循环，dp[k][i][j] = min(dp[k-1][i][j], dp[k-1][i][k]+dp[k-1][k][j])',
            'template': "# Floyd最短路\nimport sys\nlines = sys.stdin.read().strip().split('\\n')\nn, m = map(int, lines[0].split())\nINF = float('inf')\ndist = [[INF]*(n+1) for _ in range(n+1)]\nfor i in range(1, n+1):\n    dist[i][i] = 0\nfor i in range(1, m+1):\n    u, v, w = map(int, lines[i].split())\n    dist[u][v] = min(dist[u][v], w)\n    dist[v][u] = min(dist[v][u], w)\n\n# Floyd核心\n# 在此写代码\n\nq_start = m + 1\nfor i in range(q_start, len(lines)):\n    if not lines[i].strip():\n        continue\n    a, b = map(int, lines[i].split())\n    print(dist[a][b] if dist[a][b] != INF else -1)\n",
            'test_input': '4 3\n1 2 2\n2 3 1\n1 3 5\n1 3\n3 4\n',
            'answer': "import sys\nlines = sys.stdin.read().strip().split('\\n')\nn, m = map(int, lines[0].split())\nINF = float('inf')\ndist = [[INF]*(n+1) for _ in range(n+1)]\nfor i in range(1, n+1):\n    dist[i][i] = 0\nfor i in range(1, m+1):\n    u, v, w = map(int, lines[i].split())\n    dist[u][v] = min(dist[u][v], w)\n    dist[v][u] = min(dist[v][u], w)\n\nfor k in range(1, n+1):\n    for i in range(1, n+1):\n        for j in range(1, n+1):\n            if dist[i][k] + dist[k][j] < dist[i][j]:\n                dist[i][j] = dist[i][k] + dist[k][j]\n\nq_start = m + 1\nfor i in range(q_start, len(lines)):\n    if not lines[i].strip():\n        continue\n    a, b = map(int, lines[i].split())\n    print(dist[a][b] if dist[a][b] != INF else -1)\n",
            'expected': '3\n-1\n',
            'explain': '并查集：find()路径压缩+union()按秩合并。用于连通分量、环检测等图问题。',
            'url': 'https://kamacoder.com/problempage.php?pid=1155',
            'category': '图论-最短路',
        },
        {
            'id': 44,
            'title': '开发商购买土地',
            'desc': 'n×m矩阵表示每块地价值，在行或列方向划一条线分成两部分，使两部分的和之差最小。',
            'diff': 'challenge',
            'kp': ['algo_dp', 'nested_loop', 'op_arithmetic'],
            'hint': '行前缀和+列前缀和，枚举所有分割位置取最小差',
            'template': "# 开发商购买土地\nimport sys\nlines = sys.stdin.read().strip().split('\\n')\nn, m = map(int, lines[0].split())\ngrid = []\nfor i in range(1, n + 1):\n    grid.append(list(map(int, lines[i].split())))\n\n# 在此写代码\n",
            'test_input': '3 3\n1 2 3\n4 5 6\n7 8 9\n',
            'answer': "import sys\nlines = sys.stdin.read().strip().split('\\n')\nn, m = map(int, lines[0].split())\ngrid = []\nfor i in range(1, n + 1):\n    grid.append(list(map(int, lines[i].split())))\n\ntotal = sum(sum(row) for row in grid)\nrow_sum = [sum(row) for row in grid]\ncol_sum = [sum(grid[i][j] for i in range(n)) for j in range(m)]\n\nans = total\n# 按行分割\ncur = 0\nfor i in range(n - 1):\n    cur += row_sum[i]\n    ans = min(ans, abs(total - 2 * cur))\n# 按列分割\ncur = 0\nfor j in range(m - 1):\n    cur += col_sum[j]\n    ans = min(ans, abs(total - 2 * cur))\nprint(ans)\n",
            'expected': '9\n',
            'explain': '线段树：区间查询和单点更新的数据结构。build递归建树，query/modify递归操作。',
            'url': 'https://kamacoder.com/problempage.php?pid=1044',
            'category': '前缀和',
        },
        {
            'id': 30,
            'title': '字符串解压缩',
            'desc': '给定压缩字符串如 a3[b2[c]]d → abccbccbccd，解压并输出。',
            'diff': 'challenge',
            'kp': ['algo_stack_queue', 'str_methods', 'for_loop'],
            'hint': '双栈法：数字栈+字符串栈，遇[压栈，遇]弹出计算',
            'template': "# 字符串解压缩\nimport sys\nfor line in sys.stdin:\n    s = line.strip()\n    str_stack = []\n    num_stack = []\n    cur_str = ''\n    cur_num = 0\n    # 在此写代码\n    print(cur_str)\n",
            'test_input': 'a3[b2[c]]d\n',
            'answer': "import sys\nfor line in sys.stdin:\n    s = line.strip()\n    str_stack = []\n    num_stack = []\n    cur_str = ''\n    cur_num = 0\n    for ch in s:\n        if ch.isdigit():\n            cur_num = cur_num * 10 + int(ch)\n        elif ch == '[':\n            str_stack.append(cur_str)\n            num_stack.append(cur_num)\n            cur_str = ''\n            cur_num = 0\n        elif ch == ']':\n            prev_str = str_stack.pop()\n            repeat = num_stack.pop()\n            cur_str = prev_str + cur_str * repeat\n        else:\n            cur_str += ch\n    print(cur_str)\n",
            'expected': 'abccbccbccd\n',
            'explain': '字典树Trie：每个节点26个子节点指针，insert/search/startsWith三种操作。前缀匹配利器。',
            'url': 'https://kamacoder.com/problempage.php?pid=1030',
            'category': '栈',
        },
    ],
}
